bpf/kfunc: Fix error: implicit declaration of function ‘unregister_btf_kfunc_id_set’
Fix: commit 176f7f351800 ("bpf/kfunc: add modules/bpf_task_cwd_from_pid.c")
Signed-off-by: Rong Tao <rongtao@cestc.cn>