hpc: blas: why nvidia not support LtMatmul() int8
    root@notebook-useradmin-7gdd-66d74c6547-5r956:~/rongtao# ./blas -v -t matmul-int8
    CUDA BLAS 11.11.3
    test v0.0.6 (CUDA BLAS)
    M = 6, N = 5
    Testing MATMUL INT8
    ERROR: Blas cublasLtMatmulAlgoGetHeuristic(test->ltHandle, test->matmulDesc, test->layoutA, test->layoutB, test->layoutC, test->layoutC, test->pref, 1, &test->heuristic_result, &rslt) failed, the requested functionality is not supported
    No valid algorithm found! Using fallback method.
    BLAS version 111103
    ...
    ERROR: Blas cublasLtMatmul( test->ltHandle, test->matmulDesc, alpha, test->dev_A.ptr, test->layoutA, test->dev_B.ptr, test->layoutB, beta, test->dev_C.ptr, test->layoutC, test->dev_C.ptr, test->layoutC, &test->heuristic_result.algo, test->workspace, test->workspaceSize, NULL ) failed, the requested functionality is not supported
    ...

    root@notebook-useradmin-7gdd-66d74c6547-5r956:~/rongtao# ./blas -v -t matmul-int8-2
    CUDA BLAS 11.11.3
    test v0.0.6 (CUDA BLAS)
    M = 6, N = 5
    Testing MATMUL INT8 (2)
    ERROR: Blas cublasLtMatmulAlgoGetHeuristic(test->ltHandle, test->matmulDesc, test->layoutA, test->layoutB, test->layoutC, test->layoutC, test->pref, 1, &test->heuristic_result, &rslt) failed, the requested functionality is not supported
    No valid algorithm found! Using fallback method.
    BLAS version 111103
    ...
    ERROR: Blas cublasLtMatmul( test->ltHandle, test->matmulDesc, alpha, test->dev_A.ptr, test->layoutA, test->dev_B.ptr, test->layoutB, beta, test->dev_C.ptr, test->layoutC, test->dev_C.ptr, test->layoutC, &test->heuristic_result.algo, test->workspace, test->workspaceSize, NULL ) failed, the requested functionality is not supported
    ...

The MetaX also not support int8-2, see also commit 223e733448e9 ("hpc: blas: add matmul-int8-2 test but failed on MetaX BLAS 1.0.0")

Signed-off-by: Rong Tao <rongtao@cestc.cn>