fakecuda/frontend: fix: error: only virtual member functions can be marked 'override'
llvm commit 9a97a57d9ee9 ("[clang][frontend] Add support for attribute plugins for statement attributes (#110334)")
extend virtual AttrHandling handleStmtAttribute().

On llvm 14.0.6:

    [15:43:15] CXX SO.o attribute-global.cpp -> .output/attribute-global.cpp.so.o
    In file included from attribute-global.cpp:10:
    ./configs.hpp:9:19: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
    namespace fakecuda::frontend::configs {
                      ^~~~~~~~~~~~~~~~~~~
                       { namespace frontend { namespace configs
    attribute-global.cpp:14:19: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
    namespace fakecuda::frontend::attribute {
                      ^~~~~~~~~~~~~~~~~~~~~
                       { namespace frontend { namespace attribute
    attribute-global.cpp:71:34: error: only virtual member functions can be marked 'override'
                                      class Attr *&Result) const override {
                                                                 ^~~~~~~~~
    2 warnings and 1 error generated.
    make: *** [/home/rongtao/Git/tst-linux/template//targets/libso.mk:27: .output/attribute-global.cpp.so.o] Error 1

Link: https://github.com/llvm/llvm-project
Signed-off-by: Rong Tao <rongtao@cestc.cn>