cpp: unordered_map.cpp: use {string,string} as key
rongtao@NUC10:~/Git/tst-linux/cpp$ make
[09:43:50] CXX      unordered_map.cpp -> .output/unordered_map.cpp.o
In file included from /usr/include/c++/15/bits/unordered_map.h:33,
                 from /usr/include/c++/15/unordered_map:43,
                 from unordered_map.cpp:2:
/usr/include/c++/15/bits/hashtable.h: In instantiation of ‘class std::_Hashtable<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >, std::pair<const std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >, void (*)()>, std::allocator<std::pair<const std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >, void (*)()> >, std::__detail::_Select1st, std::equal_to<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >, std::hash<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >’:
/usr/include/c++/15/bits/unordered_map.h:115:18:   required from ‘class std::unordered_map<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >, void (*)()>’
  115 |       _Hashtable _M_h;
      |                  ^~~~
unordered_map.cpp:11:65:   required from here
   11 |         std::unordered_map<std::pair<std::string, std::string>, fn1_t> fn1_map2_;
      |                                                                        ^~~~~~~~~
/usr/include/c++/15/bits/hashtable.h:210:51: error: static assertion failed: hash function must be copy constructible
  210 |       static_assert(is_copy_constructible<_Hash>::value,
      |                                                   ^~~~~
/usr/include/c++/15/bits/hashtable.h:210:51: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
unordered_map.cpp: In function ‘int main()’:
unordered_map.cpp:64:18: error: use of deleted function ‘func_map::func_map()’
   64 |         func_map funcMap;
      |                  ^~~~~~~
unordered_map.cpp:13:9: note: ‘func_map::func_map()’ is implicitly deleted because the default definition would be ill-formed:
   13 |         func_map() = default;
      |         ^~~~~~~~
unordered_map.cpp: At global scope:

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64
Versions: Fedora Linux 43, Kernel 6.17.7-300.fc43.x86_64, GCC 15.2.1, glibc 2.42, LLVM 21.1.5