Doc: requirements.txt: require sphinx>=7.2.6 is enough
$ sudo pip install -r requirements.txt --break-system-packages
....
Installing collected packages: sphinx, sphinxcontrib-svg2pdfconverter, sphinxcontrib-mermaid, sphinx-rtd-theme
  Attempting uninstall: sphinx
    Found existing installation: Sphinx 7.2.6
ERROR: Cannot uninstall Sphinx 7.2.6, RECORD file not found. Hint: The package was installed by debian.

Signed-off-by: Rong Tao <rongtao@cestc.cn>
OS: Ubuntu 24.04.4 LTS
Linux: 6.17.0-1014-nvidia
Vers: LateXmk 4.83, Python 3.12.3, Sphinx 7.2.6
Envs: Arch aarch64