__STDC__.c: Fix error: C++ style comments are not allowed in ISO C90
rongtao@NUC10:~/Git/tst-linux/c$ make V=1
[14:04:17] CC E     __STDC__c98.c -> .output/__STDC__c98.E.c
gcc -E -o .output/__STDC__c98.E.c __STDC__c98.c -I../macro/ -D_GNU_SOURCE -Werror -Wall -Wstrict-prototypes -std=c89 -DSTD_C98=1
__STDC__c98.c:1:1: error: C++ style comments are not allowed in ISO C90
    1 | // SPDX-License-Identifier: GPL-3.0
      | ^
__STDC__c98.c:1:1: note: (this will be reported only once per input file)

Fix: commit 185c5aeb3753 ("iso: add ISO/IEC 9899 and ISO/IEC 14882")
Signed-off-by: Rong Tao <rongtao@cestc.cn>