libxdp: fix compile error
      CC  xsk_user.c to xsk_user.o
    xsk_user.c: In function ‘main’:
    xsk_user.c:665:15: error: implicit declaration of function ‘tl_bpf_xdp_attach’; did you mean ‘bpf_xdp_attach’? [-Wimplicit-function-declaration]
      665 |         err = tl_bpf_xdp_attach(ifindex, prog_fd, 0);
          |               ^~~~~~~~~~~~~~~~~
          |               bpf_xdp_attach
    xsk_user.c:698:9: error: implicit declaration of function ‘tl_bpf_xdp_detach’; did you mean ‘bpf_xdp_detach’? [-Wimplicit-function-declaration]
      698 |         tl_bpf_xdp_detach(ifindex, 0);
          |         ^~~~~~~~~~~~~~~~~
          |         bpf_xdp_detach
    make: *** [Makefile:51: xsk_user.o] Error 1

    rongtao@f41:~/Git/tst-linux/bpf/xdp/libxdp$ make
      CC  xsk_user.c to xsk_user.o
      CC  libbpf_wrapper.c to libbpf_wrapper.o
    libbpf_wrapper.c: In function ‘libbpf_bpf_map_update_elem’:
    libbpf_wrapper.c:71:13: error: unused variable ‘fd’ [-Werror=unused-variable]
       71 |         int fd, err = 0;
          |             ^~
    cc1: all warnings being treated as errors

Fix: commit f5b53672438a ("libbpf: wrapper use libbpf_ prefix instead of tl_ prefix")
Signed-off-by: Rong Tao <rtoax@foxmail.com>