scripts/install-deps.shL skip perf on opencloudos
    Running transaction check
    Transaction check succeeded.
    Running transaction test
    The downloaded packages were saved in cache until the next successful transaction.
    You can remove cached packages by executing 'dnf clean packages'.
    Error: Transaction test error:
      file /usr/lib64/traceevent/plugins/plugin_cfg80211.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_function.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_hrtimer.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_jbd2.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_kmem.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_kvm.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_mac80211.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_sched_switch.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_scsi.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64
      file /usr/lib64/traceevent/plugins/plugin_xen.so from install of perf-5.4.241-30.0017.19.oc8.x86_64 conflicts with file from package libtraceevent-1.5.3-1.oc8.x86_64

Signed-off-by: Rong Tao <rongtao@cestc.cn>