user.mk: Rename UID to CONFIG_UID
On ubuntu 25.10

    [21:26:47] BPF      config-map.bpf.c -> .output/config-map.bpf.o
    In file included from config-map.bpf.c:1:
    ./vmlinux.h:27111:2: error: expected identifier
     27111 |         UID = 0,
           |         ^
    <command line>:26:13: note: expanded from macro 'UID'
       26 | #define UID 1000
          |             ^

Fix: commit 70d1bd12b581 ("template: add user.mk and apply to libbpf/Makefile")
Link: commit dde051c79da8 ("libbpf: Makefile: Fix dup UID macro on ubuntu 25.04")
Signed-off-by: Rong Tao <rongtao@cestc.cn>