bpf/insn/samples: Build.mk: fix fatal error: btf_helpers.h: No such file or directory
helpers's CFLAGS add in targets/helpers.mk, if not `include helpers.mk`,
CFLAGS will not add -I.... since commit [1].

Error:

    $ make
    ....
    [2026/03/13 13:49:30] CC SO.o  .output/cgroup_acquire.so.o
    cgroup_acquire.c:11:10: fatal error: btf_helpers.h: No such file or directory
       11 | #include "btf_helpers.h"
          |          ^~~~~~~~~~~~~~~
    compilation terminated.

Fix: commit 758fda6ac6a3 ("main.mk: only include targets/helpers.mk if helpers.mk was included") [1]
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, x86_64, Physical Machine
Vers: Fedora Linux 43, Linux 6.18.16-200.fc43.x86_64, Make 4.4.1, BCC 0.35.0, LibBpf 1.6.1