libunwind: Fix: undefined reference to `_UPT_accessors'
Fix: commit 35b925a6f0a3 ("Add Makefile to compile and code specification.")
Signed-off-by: Rong Tao <rongtao@cestc.cn>