fakeCUDA: cuda_compat.h: hip: error: ‘__builtin_amdgcn_ds_bpermute’ was not declared in this scope
This commit revert part of commit b29f1d4e3fe0 ("bfloat16.cu: hip 6.3.42133-0: fix hip compile errors").

Errors:

[16:49:52] CXX SO.o runtime-hip.cpp -> .output/runtime-hip.cpp.so.o
In file included from /usr/include/hip/amd_detail/amd_hip_bf16.h:113,
                 from /usr/include/hip/hip_bf16.h:29,
                 from cuda_compat.h:48,
                 from runtime.hpp:9,
                 from runtime.cpp:3,
                 from runtime-hip.cpp:2:
/usr/include/hip/amd_detail/amd_warp_functions.h: In function ‘unsigned int __hip_ds_bpermute(int, unsigned int)’:
/usr/include/hip/amd_detail/amd_warp_functions.h:38:13: error: ‘__builtin_amdgcn_ds_bpermute’ was not declared in this scope
   38 |     tmp.i = __builtin_amdgcn_ds_bpermute(index, tmp.i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hip/amd_detail/amd_warp_functions.h: In function ‘float __hip_ds_bpermutef(int, float)’:
/usr/include/hip/amd_detail/amd_warp_functions.h:44:13: error: ‘__builtin_amdgcn_ds_bpermute’ was not declared in this scope
   44 |     tmp.i = __builtin_amdgcn_ds_bpermute(index, tmp.i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hip/amd_detail/amd_warp_functions.h: In function ‘unsigned int __hip_ds_permute(int, unsigned int)’:
/usr/include/hip/amd_detail/amd_warp_functions.h:50:13: error: ‘__builtin_amdgcn_ds_permute’ was not declared in this scope
   50 |     tmp.i = __builtin_amdgcn_ds_permute(index, tmp.i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hip/amd_detail/amd_warp_functions.h: In function ‘float __hip_ds_permutef(int, float)’:
/usr/include/hip/amd_detail/amd_warp_functions.h:56:13: error: ‘__builtin_amdgcn_ds_permute’ was not declared in this scope
   56 |     tmp.i = __builtin_amdgcn_ds_permute(index, tmp.i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hip/amd_detail/amd_warp_functions.h: In function ‘int __hip_move_dpp_N(int)’:
/usr/include/hip/amd_detail/amd_warp_functions.h:82:12: error: there are no arguments to ‘__builtin_amdgcn_mov_dpp’ that depend on a template parameter, so a declaration of ‘__builtin_amdgcn_mov_dpp’ must be available [-Wtemplate-body]
   82 |     return __builtin_amdgcn_mov_dpp(src, dpp_ctrl, row_mask, bank_mask,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hip/amd_detail/amd_warp_functions.h:82:12: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/usr/include/hip/amd_detail/amd_warp_functions.h: At global scope:
/usr/include/hip/amd_detail/amd_warp_functions.h:87:33: error: ‘__AMDGCN_WAVEFRONT_SIZE’ was not declared in this scope
   87 | static constexpr int warpSize = __AMDGCN_WAVEFRONT_SIZE;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/hip/amd_detail/amd_warp_functions.h: In function ‘long long unsigned int __ballot(int)’:
/usr/include/hip/amd_detail/amd_warp_functions.h:108:12: error: ‘__builtin_amdgcn_uicmp’ was not declared in this scope; did you mean ‘__builtin_strncmp’?
  108 |     return __builtin_amdgcn_uicmp(predicate, 0, ICMP_NE);
      |            ^~~~~~~~~~~~~~~~~~~~~~
      |            __builtin_strncmp

Signed-off-by: Rong Tao <rongtao@cestc.cn>