properties.cu: hip 5.7.31921: fix non-exist fields error
ROCm 5.7.31921 hipDeviceProp_t:

    typedef struct hipDeviceProp_t {
        char name[256];            ///< Device name.
        size_t totalGlobalMem;     ///< Size of global memory region (in bytes).
        size_t sharedMemPerBlock;  ///< Size of shared memory region (in bytes).
        int regsPerBlock;          ///< Registers per block.
        int warpSize;              ///< Warp size.
        int maxThreadsPerBlock;    ///< Max work items per work group or workgroup max size.
        int maxThreadsDim[3];      ///< Max number of threads in each dimension (XYZ) of a block.
        int maxGridSize[3];        ///< Max grid dimensions (XYZ).
        int clockRate;             ///< Max clock frequency of the multiProcessors in khz.
        int memoryClockRate;       ///< Max global memory clock frequency in khz.
        int memoryBusWidth;        ///< Global memory bus width in bits.
        size_t totalConstMem;      ///< Size of shared memory region (in bytes).
        int major;  ///< Major compute capability.  On HCC, this is an approximation and features may
                    ///< differ from CUDA CC.  See the arch feature flags for portable ways to query
                    ///< feature caps.
        int minor;  ///< Minor compute capability.  On HCC, this is an approximation and features may
                    ///< differ from CUDA CC.  See the arch feature flags for portable ways to query
                    ///< feature caps.
        int multiProcessorCount;          ///< Number of multi-processors (compute units).
        int l2CacheSize;                  ///< L2 cache size.
        int maxThreadsPerMultiProcessor;  ///< Maximum resident threads per multi-processor.
        int computeMode;                  ///< Compute mode.
        int clockInstructionRate;  ///< Frequency in khz of the timer used by the device-side "clock*"
                                   ///< instructions.  New for HIP.
        hipDeviceArch_t arch;      ///< Architectural feature flags.  New for HIP.
        int concurrentKernels;     ///< Device can possibly execute multiple kernels concurrently.
        int pciDomainID;           ///< PCI Domain ID
        int pciBusID;              ///< PCI Bus ID.
        int pciDeviceID;           ///< PCI Device ID.
        size_t maxSharedMemoryPerMultiProcessor;  ///< Maximum Shared Memory Per Multiprocessor.
        int isMultiGpuBoard;                      ///< 1 if device is on a multi-GPU board, 0 if not.
        int canMapHostMemory;                     ///< Check whether HIP can map host memory
        int gcnArch;                              ///< DEPRECATED: use gcnArchName instead
        char gcnArchName[256];                    ///< AMD GCN Arch Name.
        int integrated;            ///< APU vs dGPU
        int cooperativeLaunch;            ///< HIP device supports cooperative launch
        int cooperativeMultiDeviceLaunch; ///< HIP device supports cooperative launch on multiple devices
        int maxTexture1DLinear;    ///< Maximum size for 1D textures bound to linear memory
        int maxTexture1D;          ///< Maximum number of elements in 1D images
        int maxTexture2D[2];       ///< Maximum dimensions (width, height) of 2D images, in image elements
        int maxTexture3D[3];       ///< Maximum dimensions (width, height, depth) of 3D images, in image elements
        unsigned int* hdpMemFlushCntl;      ///< Addres of HDP_MEM_COHERENCY_FLUSH_CNTL register
        unsigned int* hdpRegFlushCntl;      ///< Addres of HDP_REG_COHERENCY_FLUSH_CNTL register
        size_t memPitch;                 ///<Maximum pitch in bytes allowed by memory copies
        size_t textureAlignment;         ///<Alignment requirement for textures
        size_t texturePitchAlignment;    ///<Pitch alignment requirement for texture references bound to pitched memory
        int kernelExecTimeoutEnabled;    ///<Run time limit for kernels executed on the device
        int ECCEnabled;                  ///<Device has ECC support enabled
        int tccDriver;                   ///< 1:If device is Tesla device using TCC driver, else 0
        int cooperativemultideviceunmatchedfunc;        ///< hip device supports cooperative launch on multiple
                                                        ///devices with unmatched functions
        int cooperativemultideviceunmatchedgriddim;     ///< hip device supports cooperative launch on multiple
                                                        ///devices with unmatched grid dimensions
        int cooperativemultideviceunmatchedblockdim;    ///< hip device supports cooperative launch on multiple
                                                        ///devices with unmatched block dimensions
        int cooperativemultideviceunmatchedsharedmem;   ///< hip device supports cooperative launch on multiple
                                                        ///devices with unmatched shared memories
        int islargebar;                  ///< 1: if it is a large pci bar device, else 0
        int asicrevision;                ///< revision of the gpu in this device
        int managedmemory;               ///< device supports allocating managed memory on this system
        int directmanagedmemaccessfromhost; ///< host can directly access managed memory on the device without migration
        int concurrentmanagedaccess;     ///< device can coherently access managed memory concurrently with the cpu
        int pageablememoryaccess;        ///< device supports coherently accessing pageable memory
                                         ///< without calling hiphostregister on it
        int pageablememoryaccessuseshostpagetables; ///< device accesses pageable memory via the host's page tables
    } hipdeviceprop_t;

errors:

[21:14:32] HIPCC    properties.cu -> .output/properties.hip.o
properties.cu:62:2: warning: ignoring return value of type 'hipError_t' declared with 'nodiscard' attribute [-Wunused-value]
   62 |         cudaGetDeviceProperties(&prop, dev);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./cuda_adapter.h:896:46: note: expanded from macro 'cudaGetDeviceProperties'
  896 | #define cudaGetDeviceProperties(prop, devid)    __cuda(GetDeviceProperties(prop, devid))
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./cuda_adapter.h:68:23: note: expanded from macro '__cuda'
   68 | # define __cuda(name)   hip##name
      |                         ^~~~~~~~~
<scratch space>:20:1: note: expanded from here
   20 | hipGetDeviceProperties
      | ^~~~~~~~~~~~~~~~~~~~~~
properties.cu:71:34: error: no member named 'uuid' in 'hipDeviceProp_t'
   71 |         printuuid("uuid", (void *)&prop.uuid, 16);
      |                                    ~~~~ ^
properties.cu:73:34: error: no member named 'luid' in 'hipDeviceProp_t'
   73 |         printuuid("luid", (void *)&prop.luid, 8);
      |                                    ~~~~ ^
properties.cu:76:10: error: no member named 'multiGpuBoardGroupID' in 'hipDeviceProp_t'
   76 |         PRINT_d(multiGpuBoardGroupID);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:85:10: error: no member named 'asyncEngineCount' in 'hipDeviceProp_t'
   85 |         PRINT_d(asyncEngineCount);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:86:10: error: no member named 'unifiedAddressing' in 'hipDeviceProp_t'
   86 |         PRINT_d(unifiedAddressing);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:97:10: error: no member named 'persistingL2CacheMaxSize' in 'hipDeviceProp_t'
   97 |         PRINT_d(persistingL2CacheMaxSize);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:98:10: error: no member named 'globalL1CacheSupported' in 'hipDeviceProp_t'
   98 |         PRINT_d(globalL1CacheSupported);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:99:10: error: no member named 'localL1CacheSupported' in 'hipDeviceProp_t'
   99 |         PRINT_d(localL1CacheSupported);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:106:11: error: no member named 'sharedMemPerMultiprocessor' in 'hipDeviceProp_t'
  106 |         PRINT_ld(sharedMemPerMultiprocessor);
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
properties.cu:67:49: note: expanded from macro 'PRINT_ld'
   67 | #define PRINT_ld(v)     printf("%s %ld\n", #v, prop.v);
      |                                                ~~~~ ^
properties.cu:107:11: error: no member named 'sharedMemPerBlockOptin' in 'hipDeviceProp_t'
  107 |         PRINT_ld(sharedMemPerBlockOptin);
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
properties.cu:67:49: note: expanded from macro 'PRINT_ld'
   67 | #define PRINT_ld(v)     printf("%s %ld\n", #v, prop.v);
      |                                                ~~~~ ^
properties.cu:108:11: error: no member named 'reservedSharedMemPerBlock' in 'hipDeviceProp_t'
  108 |         PRINT_ld(reservedSharedMemPerBlock);
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
properties.cu:67:49: note: expanded from macro 'PRINT_ld'
   67 | #define PRINT_ld(v)     printf("%s %ld\n", #v, prop.v);
      |                                                ~~~~ ^
properties.cu:115:10: error: no member named 'canUseHostPointerForRegisteredMem' in 'hipDeviceProp_t'
  115 |         PRINT_d(canUseHostPointerForRegisteredMem);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:117:10: error: no member named 'maxBlocksPerMultiProcessor' in 'hipDeviceProp_t'
  117 |         PRINT_d(maxBlocksPerMultiProcessor);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:118:10: error: no member named 'accessPolicyMaxWindowSize' in 'hipDeviceProp_t'
  118 |         PRINT_d(accessPolicyMaxWindowSize);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:136:10: error: no member named 'maxTexture1DMipmap' in 'hipDeviceProp_t'
  136 |         PRINT_d(maxTexture1DMipmap);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:142:10: error: no member named 'maxTexture2DMipmap' in 'hipDeviceProp_t'
  142 |         PRINT_d(maxTexture2DMipmap[0]);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:143:10: error: no member named 'maxTexture2DMipmap' in 'hipDeviceProp_t'
  143 |         PRINT_d(maxTexture2DMipmap[1]);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:144:10: error: no member named 'maxTexture2DLinear' in 'hipDeviceProp_t'
  144 |         PRINT_d(maxTexture2DLinear[0]);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
properties.cu:145:10: error: no member named 'maxTexture2DLinear' in 'hipDeviceProp_t'
  145 |         PRINT_d(maxTexture2DLinear[1]);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
properties.cu:65:47: note: expanded from macro 'PRINT_d'
   65 | #define PRINT_d(v)      printf("%s %d\n", #v, prop.v);
      |                                               ~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated when compiling for gfx906.
failed to execute:/usr/bin/clang++-21  -O3  -o ".output/properties.hip.o" -c -x hip properties.cu -I/usr/include/c++/15/x86_64-redhat-linux/ -I. -Wno-unused-result -I/home/rongtao/Git/tst-linux//hpc/nvidia/cuda -I/home/rongtao/Git/tst-linux//hpc/nvidia/cuda -DHAVE_HIP=1 -D__USE_HIP__=1 -DHAVE_HIPSOLVER=1 -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/usr/include -I/include

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64
Vers: Ubuntu 25.10, Linux 6.17.0-7-generic, GCC 15.2.0, glibc 2.42, LLVM 20.1.8, CUDA V12.2.140, ROCm 5.7.31921