pytorch: compile: use third_party/cpuinfo first
$ cmake --build .
....
[1/1615] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/Utils.cpp.o
FAILED: [code=1] caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/Utils.cpp.o
/usr/bin/ccache /usr/bin/c++ -DAT_BUILD_ARM_VEC256_WITH_SLEEF -DAT_PER_OPERATOR_HEADERS -DCAFFE2_BUILD_MAIN_LIB -DCAFFE2_PERF_WITH_SVE=1 -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_POSIX_FALLOCATE=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx -DUSE_EXTERNAL_MZCRC -DUSE_MIMALLOC -D_FILE_OFFSET_BITS=64 -Dtorch_cpu_EXPORTS -I/home/rongtao/Git/pytorch/pytorch/build/aten/src -I/home/rongtao/Git/pytorch/pytorch/aten/src -I/home/rongtao/Git/pytorch/pytorch/build -I/home/rongtao/Git/pytorch/pytorch -I/home/rongtao/Git/pytorch/pytorch/nlohmann -I/home/rongtao/Git/pytorch/pytorch/moodycamel -I/home/rongtao/Git/pytorch/pytorch/third_party/mimalloc/include -I/home/rongtao/Git/pytorch/pytorch/torch/csrc/api -I/home/rongtao/Git/pytorch/pytorch/torch/csrc/api/include -I/home/rongtao/Git/pytorch/pytorch/caffe2/aten/src/TH -I/home/rongtao/Git/pytorch/pytorch/build/caffe2/aten/src/TH -I/home/rongtao/Git/pytorch/pytorch/build/caffe2/aten/src -I/home/rongtao/Git/pytorch/pytorch/build/caffe2/../aten/src -I/home/rongtao/Git/pytorch/pytorch/torch/csrc -I/home/rongtao/Git/pytorch/pytorch/torch/headeronly -I/home/rongtao/Git/pytorch/pytorch/third_party/miniz-3.0.2 -I/home/rongtao/Git/pytorch/pytorch/third_party/kineto/libkineto/include -I/home/rongtao/Git/pytorch/pytorch/third_party/cpp-httplib -I/home/rongtao/Git/pytorch/pytorch/aten/src/ATen/.. -I/home/rongtao/Git/pytorch/pytorch/c10/.. -I/home/rongtao/Git/pytorch/pytorch/third_party/fmt/include -I/home/rongtao/Git/pytorch/pytorch/third_party/flatbuffers/include -isystem /home/rongtao/Git/pytorch/pytorch/third_party/protobuf/src -isystem /usr/include/eigen3 -isystem /home/rongtao/Git/pytorch/pytorch/INTERFACE -isystem /home/rongtao/Git/pytorch/pytorch/third_party/nlohmann/include -isystem /home/rongtao/Git/pytorch/pytorch/third_party/concurrentqueue -isystem /home/rongtao/Git/pytorch/pytorch/caffe2 -ffunction-sections -fdata-sections -fvisibility-inlines-hidden -DAT_BUILD_ARM_VEC256_WITH_SLEEF -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -DC10_NODEPRECATED -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-unused-parameter -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=old-style-cast -faligned-new -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-dangling-reference -Wno-error=dangling-reference -Wno-stringop-overflow -DHAVE_SVE_CPU_DEFINITION -DHAVE_SVE256_CPU_DEFINITION -DHAVE_ARM_BF16_CPU_DEFINITION -O2 -g -DNDEBUG -fPIC -fdiagnostics-color=always -D__NEON__ -Wall -Wextra -Wdeprecated -Wunused -Wno-unused-parameter -Wno-missing-field-initializers -Wno-array-bounds -Wno-unknown-pragmas -Wno-strict-overflow -Wno-strict-aliasing -Wredundant-move -Wno-interference-size -Wno-maybe-uninitialized -fvisibility=hidden -fopenmp -MD -MT caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/Utils.cpp.o -MF caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/Utils.cpp.o.d -o caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/Utils.cpp.o -c /home/rongtao/Git/pytorch/pytorch/aten/src/ATen/cpu/Utils.cpp
/home/rongtao/Git/pytorch/pytorch/aten/src/ATen/cpu/Utils.cpp: In function ‘bool at::cpu::is_amx_tile_supported()’:
/home/rongtao/Git/pytorch/pytorch/aten/src/ATen/cpu/Utils.cpp:46:34: error: ‘cpuinfo_has_x86_amx_tile’ was not declared in this scope; did you mean ‘cpuinfo_has_x86_mmx_plus’?
   46 |   return cpuinfo_initialize() && cpuinfo_has_x86_amx_tile();
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                  cpuinfo_has_x86_mmx_plus
/home/rongtao/Git/pytorch/pytorch/aten/src/ATen/cpu/Utils.cpp: In function ‘bool at::cpu::is_amx_fp16_supported()’:
/home/rongtao/Git/pytorch/pytorch/aten/src/ATen/cpu/Utils.cpp:54:37: error: ‘cpuinfo_has_x86_amx_fp16’ was not declared in this scope; did you mean ‘cpuinfo_has_x86_avx512fp16’?
   54 |   return is_amx_tile_supported() && cpuinfo_has_x86_amx_fp16();
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                     cpuinfo_has_x86_avx512fp16
[2/1615] Linking CXX shared library lib/libc10.so

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU Cortex-X925 Cortex-A725, Arch aarch64, Physical Machine
Vers: Ubuntu 24.04, Linux 6.14.0-1015-nvidia, BASH 5.2.21