bpftrace: playground: concat 2 strings to a new string
Note:

bpf function could not pass more than 5 parameters, for example:

     45 size_t __bpf_str_concat(char *dst, size_t dst_sz, const char *s1, size_t s1_sz,
     46                         const char *s2, size_t s2_sz)

Will cause:

    $ sudo ./str_concat.bt
    1 error generated.
    ./str_concat.bt:6:3-28: ERROR: failed to build
      import "str_concat.bpf.c";
      ~~~~~~~~~~~~~~~~~~~~~~~~~
    HINT: str_concat.bpf.c:45:8: error: stack arguments are not supported
       45 | size_t __bpf_str_concat(char *dst, size_t dst_sz, const char *s1, size_t s1_sz,
          |        ^

Link: https://github.com/bpftrace/bpftrace/pull/5231
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU: Cortex-X925 Cortex-A725, Arch aarch64
Vers: Ubuntu 24.04, Linux 6.17.0-1014-nvidia, BPFTrace 0.26.0, GCC 13.3.0, GLibc 2.39, LibBpf 1.3.0