simd.c: Fix: error: pointer targets in passing argument 1 of ‘getcpu’ differ in signedness
Error:

[2026/02/13 16:00:29] CC       simd.c -> .output/simd.o
simd.c: In function ‘main’:
simd.c:827:16: error: pointer targets in passing argument 1 of ‘getcpu’ differ in signedness [-Werror=pointer-sign]
  827 |         getcpu(&cpu, NULL);
      |                ^~~~
      |                |
      |                int *
In file included from /usr/include/sched.h:43,
                 from simd.c:22:
/usr/include/bits/sched.h:92:20: note: expected ‘unsigned int *’ but argument is of type ‘int *’
   92 | extern int getcpu (unsigned int *, unsigned int *) __THROW;
      |                    ^~~~~~~~~~~~~~

Fix: commit b96d07d2082f ("getcpu(2): glibc 2.28 not have getcpu() wrapper")
Link: commit 94d62a566a35 ("libbpf: perf_event.c: Fix ksym_helpers compile error")
Signed-off-by: Rong Tao <rtoax@foxmail.com>
Envs: CPU Phytium, Arch aarch64, Physical Machine
Vers: CCLinux 22.09.2, Linux 5.15.131-29.cl9.aarch64, GCC 11.3.1, glibc 2.34