syscall/samples: readlink2.cpp: fix undefined reference to `std::filesystem::canonical
compile with gcc 8.5.0, has this error, thus, need gcc 8.6 at least, if
error on other gcc version, modify minor number.

Fix: commit 6819a5fbb1be ("syscall/samples: readlink2.cpp: todo: undefined reference to `std::filesystem::canonical")
Signed-off-by: Rong Tao <rongtao@cestc.cn>