syscall: SIGILL.c: Fix Error: unknown mnemonic `udf' -- `udf #0'
 [sub-dir] build setjmp.build
  CC  signal.c to signal.o
/tmp/ccMLDnjq.s: Assembler messages:
/tmp/ccMLDnjq.s:86: Error: unknown mnemonic `udf' -- `udf #0'
make[1]: *** [Makefile:37: signal.o] Error 1
make: *** [Makefile:154: setjmp.build] Error 2

See also commit 077ff538dc16 ("instructions: invalid_opcode.h: Fix
Error: unknown mnemonic `udf' -- `udf #0'")

Signed-off-by: Rong Tao <rongtao@cestc.cn>