fakecuda/frontend: fix: error: no member named 'AS_C23' in 'clang::ParsedAttr'; did you mean 'AS_C2x'
llvm commit 0ce056a814f8 ("[C23] Rename C2x -> C23; NFC")
llvmorg-18-init-1905-g0ce056a814f8

    [15:25:31] CXX SO.o attribute-device.cpp -> .output/attribute-device.cpp.so.o
    attribute-device.cpp:14:19: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
    namespace fakecuda::frontend::attribute {
                      ^~~~~~~~~~~~~~~~~~~~~
                       { namespace frontend { namespace attribute
    attribute-device.cpp:29:21: error: no member named 'AS_C23' in 'clang::ParsedAttr'; did you mean 'AS_C2x'?
                                                     {ParsedAttr::AS_C23, DEVICE_ATTR_NAME},
                                                      ~~~~~~~~~~~~^~~~~~
                                                                  AS_C2x
    /usr/include/clang/Basic/AttributeCommonInfo.h:33:5: note: 'AS_C2x' declared here
        AS_C2x,
        ^
    attribute-device.cpp:97:21: error: no member named 'AS_C23' in 'clang::ParsedAttr'; did you mean 'AS_C2x'?
                                                     {ParsedAttr::AS_C23, DEVICE_BUILTIN_ATTR_NAME},
                                                      ~~~~~~~~~~~~^~~~~~
                                                                  AS_C2x
    /usr/include/clang/Basic/AttributeCommonInfo.h:33:5: note: 'AS_C2x' declared here
        AS_C2x,
        ^
    1 warning and 4 errors generated.

Link: https://github.com/llvm/llvm-project
Signed-off-by: Rong Tao <rongtao@cestc.cn>