qemu-vm.sh: TMPDIR should not be readonly variable
./qemu-vm.sh --dry-run --name vmname-puEdI --kernel vmlinux
./qemu-vm.sh: line 923: TMPDIR: readonly variable
sudo rm -rf
ERROR: qemu-vm running failed
ERROR: Test qemu-vm failed

Fixes: 477372dd2bef ("qemu-vm.sh: rename tmpdir to readonly TMPDIR")
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Vers: Fedora Linux 44 (Workstation Edition), Linux 7.1.10-200.fc44.x86_64, Qemu 10.0.50, bash 5.3.9
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64