avx: test-asm.S: fix compile error
[2026/03/10 11:13:37] LD       test-asm
cc -o test-asm .output/test-asm.o .output/test-asm.S.o test-asm.o
/usr/bin/ld: test-asm.o: in function `main':
/home/rongtao/Git/tst-linux/insn/examples/avx/test-asm.c:7: multiple definition of `main'; .output/test-asm.o:/home/rongtao/Git/tst-linux/insn/examples/avx/test-asm.c:7: first defined here

Fix: commit 11145cbb38a3 ("targets/exe.mk: Automatically add target to the .o dependency")
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, x86_64, Physical Machine
Vers: Fedora Linux 43, Linux 6.18.16-200.fc43.x86_64, Make 4.4.1