c/param-pass: Fix error: a function definition without a prototype is deprecated
Swap CC=clang in Makefile:

    param-pass.c:15:6: error: a function definition without a prototype is
    deprecated in all versions of C and is not supported in C2x
    [-Werror,-Wdeprecated-non-prototype]
       15 | void func3(a, b, c, d, e, f, g, h)
          |      ^

Signed-off-by: Rong Tao <rongtao@cestc.cn>