github-ci: fix: Failed to disable unit: Unit file sphinx-serve-tl.service does not exist.
> Run sudo make install
Uninstall
Failed to disable unit: Unit file sphinx-serve-tl.service does not exist.
make: *** [Makefile:133: uninstall] Error 1
Error: Process completed with exit code 2.

Link: https://github.com/Rtoax/test-linux/actions/runs/29970594878/job/89091599623
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: Arch x86_64
Vers: Fedora Linux 44 (Workstation Edition), Linux 7.1.4-200.fc44.x86_64, LateXmk 4.88, bash 5.3.9, Sphinx 8.2.3