bpf/c: test cgroup_from_id but failed
    rongtao@NUC10:~/Git/tst-linux/bpf/c$ sudo ./kprobe cgroup_from_id tracepoint
    ./kprobe [trace_printk|cgroup_from_id] [tracepoint]
    struct cgroup *bpf_cgroup_from_id(u64 cgid);
    void bpf_cgroup_release(struct cgroup *cgrp);
    Prog cgroup_from_id has 6 insns
    ERROR: failed to load prog 'Invalid argument'

Test: commit b43312747dcb ("bpf/insn/samples: add bpf_cgroup_from_id() test")
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64
Versions: Fedora Linux 43, Kernel 6.17.7-300.fc43.x86_64, GCC 15.2.1, glibc 2.42, LLVM 21.1.5, BCC 0.35.0, LIBBPF 1.6.1