qemu-vm.sh: fix create failed error
vm tmpdir was created in config_vm_tmpdir() before config_basic(), thus,
we should move the tmpdir check into config_vm_tmpdir() before directory
creation.

    rongtao@NUC10:~/Git/tst-linux/cxl$ DAEMON=1 ./vm.sh
    Startup: mkdir -p /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy
    Done: mkdir -p /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy
    Startup: touch /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/info.sh /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/cmds.sh /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/qemu-command.sh
    Done: touch /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/info.sh /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/cmds.sh /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/qemu-command.sh
    touch /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/info.sh /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/cmds.sh /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/qemu-command.sh
    Startup: chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/info.sh
    Done: chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/info.sh
    chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/info.sh
    Startup: chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/cmds.sh
    Done: chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/cmds.sh
    chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/cmds.sh
    Startup: chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/qemu-command.sh
    Done: chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/qemu-command.sh
    chmod +x /tmp/qemu-vm/cxl-custom-cxl-vmem-4way-dvJy/qemu-command.sh
    ERROR: VM 'cxl-custom-cxl-vmem-4way-dvJy' already exist in 'cxl-custom-cxl-vmem-4way-dvJy', see 'qemu-vm list -a'

Signed-off-by: Rong Tao <rongtao@cestc.cn>
OS: Fedora Linux 44 (Workstation Edition)
Linux: 7.2.7-200.fc44.x86_64
Vers: Qemu 11.1.50, bash 5.3.9
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64