procfs: pagemap.c: Fix undefined reference
    tst-linux/fs$ make
     [sub-dir] build procfs.build
      CC  pagemap.c to pagemap.o
    pagemap.c: In function ‘main’:
    pagemap.c:430:17: warning: implicit declaration of function ‘proc_pid_maps_display_2’ [-Wimplicit-function-declaration]
      430 |                 proc_pid_maps_display_2(stdout, "virt2phy: ");
          |                 ^~~~~~~~~~~~~~~~~~~~~~~
      LD  pagemap
    /usr/bin/ld: pagemap.o: in function `main':
    pagemap.c:(.text+0x713): undefined reference to `proc_pid_maps_display_2'
    collect2: error: ld returned 1 exit status
    make[2]: *** [Makefile:43: pagemap] Error 1
    make[1]: *** [Makefile:61: process.build] Error 2
    make: *** [Makefile:27: procfs.build] Error 2

Fix: commit fc499c96adbc ("libs/proc: Add proc_pid_maps_display_2() and apply to mm/virt2phy")
Signed-off-by: Rong Tao <rtoax@foxmail.com>