cuda/samples: memory.cu: fix error
On luca:

[17:02:42.468][HCR][E]hc_runtime_api.cpp       :1032: 1623448: [ffffad14cc20] hcMemcpy: Returned hcErrorInvalidValue
ERROR: dev_mem_copy:57 Call cudaMemcpy(from_mem, to_mem, SZ_MEM, kind) failed, invalid argument

Fix: commit e7d54642f7c8 ("cuda/samples: memory.cu: call cudaMemcpy()")
Signed-off-by: Rong Tao <rongtao@cestc.cn>