libbpf: Makefile: Fix compile errors
      BPF  config-map.bpf.c to config-map.bpf.o
    In file included from config-map.bpf.c:5:
    ./bpf_misc.h:44:8: error: redefinition of 'bpf_devmap_val'
       44 | struct bpf_devmap_val {
          |        ^
    ./vmlinux.h:46787:8: note: previous definition is here
     46787 | struct bpf_devmap_val {
           |        ^
    In file included from config-map.bpf.c:5:
    ./bpf_misc.h:58:8: error: redefinition of 'bpf_cpumap_val'
       58 | struct bpf_cpumap_val {
          |        ^
    ./vmlinux.h:46114:8: note: previous definition is here
     46114 | struct bpf_cpumap_val {
           |        ^
    2 errors generated.
    make: *** [Makefile:241: config-map.bpf.o] Error 1

      CC  xdp.c to xdp.o
    In file included from xdp.c:26:
    bpf_misc.h:9:2: error: #error Not support arch
        9 | #error Not support arch
          |  ^~~~~
    make: *** [Makefile:252: xdp.o] Error 1

Fix: commit ff4c217ed09e ("libbpf: Fix compile errors Kylin V10 SP3 4.19.90-52.43.v2207.ky10.x86_64")
Signed-off-by: Rong Tao <rongtao@cestc.cn>