pragma: clang_loop_unroll.c: use vmlinux.h instead of linux/types.h if BPF
rongtao@NUC11-Deb12:~/Git/tst-linux/compiler/pragma$ make V=1
make: Entering directory '/home/sda/rongtao/Git/rtoax/test-linux/compiler/pragma'
vdso.mk:35: "WARNING: Not found /lib/modules/6.12.105+deb13-amd64/vdso/vdso64.so, use dump linux-vdso.so.1 instead"
 CLANG BPF        .output/clang_loop_unroll.bpf.o
/usr/bin/clang -MMD -MT .output/clang_loop_unroll.bpf.o -MF .output/clang_loop_unroll.bpf.o.d -c clang_loop_unroll.bpf.c -o .output/clang_loop_unroll.bpf.o -I. -I.output/ -O2 -g -target bpf -mlittle-endian -mcpu=v3 -std=gnu89 -Drestrict= -DCONFIG_UID=1000 -D__IN_BPF__=1 -D__TARGET_ARCH_x86 -DSUPPORT_BPF_MAP_LOOKUP_ELEM=1 -DSUPPORT_BPF_MAP_UPDATE_ELEM=1 -DSUPPORT_BPF_MAP_DELETE_ELEM=1 -DSUPPORT_BPF_TRACE_PRINTK=1 -DSUPPORT_BPF_PERF_EVENT_READ=1 -DSUPPORT_BPF_PERF_EVENT_OUTPUT=1 -DSUPPORT_BPF_PERF_EVENT_READ_VALUE=1 -DSUPPORT_BPF_SPIN_LOCK=1 -DSUPPORT_BPF_SPIN_UNLOCK=1 -DSUPPORT_BPF_SEND_SIGNAL=1 -DSUPPORT_BPF_SEND_SIGNAL_THREAD=1 -DSUPPORT_BPF_PROBE_READ_KERNEL_STR=1 -DSUPPORT_BPF_FOR_EACH_MAP_ELEM=1 -DSUPPORT_BPF_SNPRINTF=1 -DSUPPORT_BPF_GET_FUNC_IP=1 -DSUPPORT_BPF_LOOP=1 -DSUPPORT_BPF_STRNCMP=1 -DSUPPORT_BPF_COPY_FROM_USER_TASK=1 -DSUPPORT_BPF_MAP_LOOKUP_PERCPU_ELEM=1 -DSUPPORT_BPF_DYNPTR_FROM_MEM=1 -DSUPPORT_BPF_DYNPTR_READ=1 -DSUPPORT_BPF_DYNPTR_WRITE=1 -DSUPPORT_BPF_RINGBUF_RESERVE_DYNPTR=1 -DSUPPORT_BPF_RINGBUF_SUBMIT_DYNPTR=1 -DSUPPORT_BPF_RINGBUF_DISCARD_DYNPTR=1 -DSUPPORT_BPF_CGRP_STORAGE_GET=1 -DSUPPORT_BPF_TASK_FROM_PID=1 -DSUPPORT_BPF_RCU_READ_LOCK=1 -DSUPPORT_BPF_RCU_READ_UNLOCK=1 -DSUPPORT_BPF_DYNPTR_FROM_SKB=1 -DSUPPORT_BPF_CGROUP_FROM_ID=1 -DSUPPORT_BPF_CGROUP_ACQUIRE=1 -DSUPPORT_BPF_DYNPTR_FROM_XDP=1 -DSUPPORT_BPF_DYNPTR_SLICE=1 -DSUPPORT_BPF_DYNPTR_SLICE_RDWR=1 -DSUPPORT_BPF_ITER_TASK_VMA_NEW=1 -DSUPPORT_BPF_ITER_TASK_VMA_NEXT=1 -DSUPPORT_BPF_ITER_TASK_VMA_DESTROY=1 -DSUPPORT_BPF_PATH_D_PATH=1 -DSUPPORT_BPF_GET_TASK_EXE_FILE=1 -DSUPPORT_BPF_PUT_FILE=1 -Wno-missing-declarations
In file included from clang_loop_unroll.bpf.c:11:
/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
1 error generated.

Signed-off-by: Rong Tao <rtoax@foxmail.com>
Vers: Debian GNU/Linux 13 (trixie), Linux 6.12.105+deb13-amd64, GCC 14.2.0, GLibc 2.41
Envs: Arch x86_64