libbpf: Makefile: bpftool: Fix Error: unrecognized option '-L'
  SKEL  syscall.bpf.o to syscall.skel.h
Error: unrecognized option '-L'
Usage: bpftool [OPTIONS] OBJECT { COMMAND | help }
       bpftool batch file FILE
       bpftool version

Fix: commit c2abfcfbc746 ("bpf: Test BPF_PROG_TYPE_SYSCALL")
Link: https://docs.ebpf.io/linux/program-type/BPF_PROG_TYPE_SYSCALL/
Signed-off-by: Rong Tao <rongtao@cestc.cn>