hpcc-envs.sh: fix libhcruntime.so: undefined reference to `VL1_CACHE_POLICY'
You need to set hpcc env, to fix:

[16:05:06] HTCC LD  .output/attribute.hpcc.o -> attribute-hpcc
/opt/hpcc-2.33.1/htgpu_llvm//bin/htcc -o attribute-hpcc .output/attribute.hpcc.o .output/cuda_helpers.hpcc.o -nodefaultrpath -lhccl -lhcblas -lhcblasLt -lhcfft -lhcrand -lhcsparse
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `VL1_CACHE_POLICY'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_MALLOC_POLICY'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_TRACING_MODE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_PRIORITY_QUEUE_POLICY'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_RING_BUFFER_SIZE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `KERNEL_BLIT_SELECT'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhccompiler.so: undefined reference to `HPCC_TRAP_HANDLER'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_MONITOR_HANG_TIMEOUT'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_LAUNCH_BLOCKING'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_GRAPH_TRACE_MODE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_GRAPH_LAUNCH_MODE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_DMA_SCHEDULE_POLICY'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhccompiler.so: undefined reference to `HPCC_LAUNCH_MODE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_BACK_TRACE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_MEMCPY_MODE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_GRAPH_MEMCPY_MODE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_DIRECT_DISPATCH'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `HPCC_MPS_MODE'
/usr/bin/ld: /opt/hpcc-2.33.1/lib/libhcruntime.so: undefined reference to `MCDBG_DEVICE_IMAGE_MALLOC_MODE'

Signed-off-by: Rong Tao <rongtao@cestc.cn>