libbpf: execsnoop: Makefile: Use c/skel/Makefile
Error:

    bpftool gen skeleton hello-buffer-config.bpf.o > hello-buffer-config.skel.h
    libbpf: BTF is required, but is missing or corrupted.
    Error: failed to open BPF object file: No such file or directory
    make: *** [Makefile:50: hello-buffer-config.skel.h] Error 255

Fix: compile hello-buffer-config.bpf.o with '-g'

Signed-off-by: Rong Tao <rongtao@cestc.cn>