libxdp: fix compile error
  CC  xsk_user.c to xsk_user.o
xsk_user.c: In function ‘sig_handler’:
xsk_user.c:94:9: error: implicit declaration of function ‘stop_read_trace_pipe’; did you mean ‘read_trace_pipe’? [-Wimplicit-function-declaration]
   94 |         stop_read_trace_pipe();
      |         ^~~~~~~~~~~~~~~~~~~~
      |         read_trace_pipe
make[3]: *** [Makefile:51: xsk_user.o] Error 1
make[2]: *** [../../template/subdir-footer.mk:7: /home/sdb/Git/tst-linux/bpf/xdp/libxdp.build] Error 2
make[1]: *** [../template/subdir-footer.mk:7: /home/rongtao/Git/tst-linux/bpf/xdp.build] Error 2
Failed U bpf

Fix: commit 8e0358e92703 ("libbpf: trace_helpers.c: Rename stop_read_trace_pipe() to read_trace_pipe_stop()")
Signed-off-by: Rong Tao <rongtao@cestc.cn>