__attribute__: Build.mk: Fix compile error of aligned.c
rongtao@NUC10-VM-F42:~/Git/tst-linux/compiler/attribute$ make
 ....
 CC               .output/aligned.o
aligned.c:8:10: fatal error: attribute/compiler.h: No such file or directory
    8 | #include "attribute/compiler.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Fixes: a8f0d2c2caf3 ("pragma: pack.h: forgot attribute/ path for compiler.h")
Signed-off-by: Rong Tao <rongtao@cestc.cn>