cuda/file: fix compile error
[2026/02/12 16:56:26] LSCC     hello.cu -> .output/hello.luca.o
hello.cu:66:2: error: use of undeclared identifier 'cudaMalloc'
        cudaMalloc(&devPtr, bufferSize);
        ^
hello.cu:67:2: error: use of undeclared identifier 'cudaMemset'
        cudaMemset(devPtr, 0xAB, bufferSize);
        ^
hello.cu:80:2: error: use of undeclared identifier 'cudaFree'
        cudaFree(devPtr);
        ^
3 errors generated when compiling for host.

Fix: commit 67df2a9fc552 ("cuda/fft: use adapter/cufft.h  instead of cuda_compat.h")
Signed-off-by: Rong Tao <rtoax@foxmail.com>
Envs: CPU Hygon C86-4G (OPN:7490), Arch x86_64, Physical Machine, Lingspeed X710Ex8
Vers: Kylin Linux Advanced Server V10, Linux 4.19.90-52.23.v2207.gfb01.ky10.x86_64, GCC 7.3.0, glibc 2.28, LUCA 3.2.1