scripts: clang-format.sh: fix grep -v -v error
$ ./clang-format.sh
grep: clang-format did not modify any files: No such file or directory
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

Fix: commit 8803c17c538c ("vpu.cu: luca: test lcVpueCtrl()")
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU Hygon C86-4G 7490 64-core Processor, Arch x86_64, Physical Machine
Vers: CCLinux 22.09.2, Linux 5.15.131-26.cl9.x86_64, BASH 5.1.8