pragma: unroll: compile with __IN_BPF__
 CLANG BPF        .output/clang_loop_unroll.bpf.o
/usr/bin/clang -MMD -MT .output/clang_loop_unroll.bpf.o -MF .output/clang_loop_unroll.bpf.o.d -c clang_loop_unroll.bpf.c -o .output/clang_loop_unroll.bpf.o -I. -I.output/ -O2 -g -target bpf -mlittle-endian -mcpu=v3 -std=gnu89 -Drestrict= -DCONFIG_UID=1000 -D__TARGET_ARCH_x86 -DSUPPORT_BPF_MAP_LOOKUP_ELEM=1 -DSUPPORT_BPF_MAP_UPDATE_ELEM=1 -DSUPPORT_BPF_MAP_DELETE_ELEM=1 -DSUPPORT_BPF_FOR_EACH_MAP_ELEM=1 -DSUPPORT_BPF_MAP_LOOKUP_PERCPU_ELEM=1 -DSUPPORT_BPF_SPIN_LOCK=1 -DSUPPORT_BPF_SPIN_UNLOCK=1 -DSUPPORT_BPF_TRACE_PRINTK=1 -DSUPPORT_BPF_PERF_EVENT_READ=1 -DSUPPORT_BPF_PERF_EVENT_OUTPUT=1 -DSUPPORT_BPF_PERF_EVENT_READ_VALUE=1 -DSUPPORT_BPF_SEND_SIGNAL=1 -DSUPPORT_BPF_SEND_SIGNAL_THREAD=1 -DSUPPORT_BPF_PROBE_READ_KERNEL_STR=1 -DSUPPORT_BPF_SNPRINTF=1 -DSUPPORT_BPF_LOOP=1 -DSUPPORT_BPF_STRNCMP=1 -DSUPPORT_BPF_COPY_FROM_USER_TASK=1 -DSUPPORT_BPF_DYNPTR_FROM_MEM=1 -DSUPPORT_BPF_DYNPTR_READ=1 -DSUPPORT_BPF_DYNPTR_WRITE=1 -DSUPPORT_BPF_RINGBUF_RESERVE_DYNPTR=1 -DSUPPORT_BPF_RINGBUF_SUBMIT_DYNPTR=1 -DSUPPORT_BPF_RINGBUF_DISCARD_DYNPTR=1 -DSUPPORT_BPF_CGRP_STORAGE_GET=1 -DSUPPORT_BPF_TASK_FROM_PID=1 -DSUPPORT_BPF_DYNPTR_FROM_SKB=1 -DSUPPORT_BPF_CGROUP_FROM_ID=1 -DSUPPORT_BPF_CGROUP_ACQUIRE=1 -DSUPPORT_BPF_DYNPTR_FROM_XDP=1 -DSUPPORT_BPF_DYNPTR_SLICE=1 -DSUPPORT_BPF_DYNPTR_SLICE_RDWR=1 -DSUPPORT_BPF_ITER_TASK_VMA_NEW=1 -DSUPPORT_BPF_ITER_TASK_VMA_NEXT=1 -DSUPPORT_BPF_ITER_TASK_VMA_DESTROY=1 -DSUPPORT_BPF_PATH_D_PATH=1 -DSUPPORT_BPF_GET_TASK_EXE_FILE=1 -DSUPPORT_BPF_PUT_FILE=1 -DSUPPORT_BPF_COPY_FROM_USER_TASK_STR=1 -DSUPPORT_BPF_RBTREE_ROOT=1 -DSUPPORT_BPF_RBTREE_LEFT=1 -DSUPPORT_BPF_RBTREE_RIGHT=1 -DSUPPORT_BPF_STRCMP=1 -DSUPPORT_BPF_STRLEN=1 -DSUPPORT_BPF_STRNLEN=1 -DSUPPORT_BPF_STRNSTR=1 -DSUPPORT_BPF_STRSTR=1 -DSUPPORT_BPF_DYNPTR_FROM_SKB_META=1 -DSUPPORT_BPF_STRCASECMP=1 -DSUPPORT_BPF_STRCASESTR=1 -DSUPPORT_BPF_STRNCASESTR=1 -DSUPPORT_BPF_STRNCASECMP=1 -Wno-missing-declarations
In file included from clang_loop_unroll.bpf.c:8:
In file included from /usr/include/stdio.h:444:
/usr/include/bits/floatn.h:83:52: error: unsupported machine mode '__TC__'
   83 | typedef _Complex float __cfloat128 __attribute__ ((__mode__ (__TC__)));
      |                                                    ^
/usr/include/bits/floatn.h:97:9: error: __float128 is not supported on this target
   97 | typedef __float128 _Float128;
      |         ^
2 errors generated.

Signed-off-by: Rong Tao <rtoax@foxmail.com>
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64
Vers: Fedora Linux 44 (Workstation Edition), Linux 7.1.4-200.fc44.x86_64, GCC 16.1.1, GLibc 2.43, LibBpf 1.8.0, Make 4.4.1, Pahole 1.30