ai/models/stella: Fix: RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Error:

$ ./xformers.py
Traceback (most recent call last):
  File "/LLM-MODEL/./stella-base-zh-2-1.py", line 21, in <module>
    vectors = normalize(vectors, norm="l2", axis=1, )
  File "/opt/conda/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_data.py", line 1979, in normalize
    X = check_array(
  File "/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1053, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/utils/_array_api.py", line 757, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 1196, in __array__
    return self.numpy().astype(dtype, copy=False)
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

modelscope==1.34.0
sentence-transformers==5.3.0.dev0
transformers==4.57.3

Signed-off-by: Rong Tao <rtoax@foxmail.com>
Envs: CPU Hygon C86-4G (OPN:7470), Arch x86_64, Physical Machine
Vers: CCLinux 22.09.2, Linux 5.15.131-28.cl9.x86_64, Python 3.10.10