cuda/pti: fix compile error
[2026/02/12 17:29:36] LSCC     subscribe.cu -> .output/subscribe.luca.o
subscribe.cu:96:2: error: use of undeclared identifier 'cudaMalloc'
        cudaMalloc(&mem, 1024);
        ^
subscribe.cu:107:2: error: use of undeclared identifier 'cudaFree'
        cudaFree(mem);
        ^
subscribe.cu:108:2: error: use of undeclared identifier 'cudaDeviceSynchronize'; did you mean 'lcDeviceSynchronize'?
        cudaDeviceSynchronize();
        ^~~~~~~~~~~~~~~~~~~~~
        lcDeviceSynchronize

Fix: commit 8f73d13ecbbb ("cuda/pti: use adapter/cupti.h instead of cuda_compat.h")
Signed-off-by: Rong Tao <rtoax@foxmail.com>
Envs: CPU Hygon C86-4G (OPN:7490), Arch x86_64, Physical Machine, Lingspeed X710Ex8
Vers: Kylin Linux Advanced Server V10, Linux 4.19.90-52.23.v2207.gfb01.ky10.x86_64, LUCA 3.2.1