todo: bpf/insn/samples: call bpf_iter_task_vma_new with NULL args
rongtao@ubuntu:~/Git/tst-linux/bpf/c$ sudo ./bpfprobe  -t tracepoint -h iter_task_vma_new
int *bpf_iter_task_vma_new(struct bpf_iter_task_vma *it, struct task_struct *task, u64 addr) = btf_id 87770;
void *bpf_iter_task_vma_destroy(struct bpf_iter_task_vma *it) = btf_id 87767;
Prog iter_task_vma_new has 6 insns
bpf(2): load iter_task_vma_new, fd -1
ERROR: failed to load prog 'Permission denied'
b7 01 00 00 00 00 00 00
b7 02 00 00 00 00 00 00
b7 03 00 00 00 00 00 00
85 20 00 00 da 56 01 00
b7 00 00 00 00 00 00 00
95 00 00 00 00 00 00 00
0: R1=ctx() R10=fp0
0: (b7) r1 = 0                        ; R1_w=0
1: (b7) r2 = 0                        ; R2_w=0
2: (b7) r3 = 0                        ; R3_w=0
3: (85) call bpf_iter_task_vma_new#87770
Possibly NULL pointer passed to trusted arg0
processed 4 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read

Link: commit 6a4323ae2d0a ("todo: bpf/insn/samples: test bpf_iter_task_vma_new()")
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64
Versions: Ubuntu 25.10, Kernel 6.17.0-6-generic, GCC 15.2.0, glibc 2.42, LLVM 20.1.8, BCC 0.35.0, LIBBPF 1.6.2