libbpf: xdp.c: xskmap: Fix  multiple definition of `display_xdp_ring_offset'
      CC(LIB)  libxdp_helpers.c to libxdp_helpers.o
      LD  xdp_xskmap
    /usr/bin/ld: libxdp_helpers.o: in function `display_xdp_ring_offset':
    /home/rongtao/Git/tst-linux/bpf/libbpf/libxdp_helpers.c:141: multiple definition of `display_xdp_ring_offset'; xdp_xskmap.o:/home/rongtao/Git/tst-linux/bpf/libbpf/xdp_xskmap.c:132: first defined here
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:264: xdp_xskmap] Error 1

Fix: commit ed2c90590273 ("libxdp: xsk_user.c: Display struct xdp_mmap_offsets")
Signed-off-by: Rong Tao <rongtao@cestc.cn>