syscall: fcntl: F_ADD_SEALS.c: Fix error
 [sub-dir] build /home/sda/git-repos/test-linux/syscall/samples/fcntl.build
  CC  F_ADD_SEALS.c to F_ADD_SEALS.o
F_ADD_SEALS.c: In function ‘main’:
F_ADD_SEALS.c:50:14: error: implicit declaration of function ‘sys_memfd_create’; did you mean ‘memfd_create’? [-Wimplicit-function-declaration]
   50 |         fd = sys_memfd_create(name, MFD_ALLOW_SEALING);
      |              ^~~~~~~~~~~~~~~~
      |              memfd_create
make[2]: *** [Makefile:57: F_ADD_SEALS.o] Error 1
make[1]: *** [Makefile:150: /home/sda/git-repos/test-linux/syscall/samples/fcntl.build] Error 2
make: *** [Makefile:19: /home/rongtao/Git/tst-linux/syscall/samples.build] Error 2

Fix: commit c8ae42b50e3b ("syscall: memfd: Code style")
Signed-off-by: Rong Tao <rongtao@cestc.cn>