cuda_adapter.h: fix rocm hip hipGetErrorName() compile error
[10:14:31] HIPCC    rtc.cu -> .output/rtc.hip.o
rtc.cu:80:2: error: no matching function for call to 'hipGetErrorName'
   80 |         CHECK_CUDA_ERROR_EXIT(cuModuleLoadData(&module, bc));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:25:37: note: expanded from macro 'CHECK_CUDA_ERROR_EXIT'
   25 | #define CHECK_CUDA_ERROR_EXIT(expr) CHECK_CUDA_ERROR(expr, exit(-1))
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:17:4: note: expanded from macro 'CHECK_CUDA_ERROR'
   17 |                         cuGetErrorName(__result, &__err_name);               \
      |                         ^~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:131:24: note: expanded from macro 'cuGetErrorName'
  131 | #define cuGetErrorName __cu(GetErrorName)
      |                        ^~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:72:21: note: expanded from macro '__cu'
   72 | # define __cu(name)     hip##name
      |                         ^~~~~~~~~
<scratch space>:330:1: note: expanded from here
  330 | hipGetErrorName
      | ^~~~~~~~~~~~~~~
/usr/include/hip/hip_runtime_api.h:2486:13: note: candidate function not viable: requires single argument 'hip_error', but 2 arguments were provided
 2486 | const char* hipGetErrorName(hipError_t hip_error);
      |             ^               ~~~~~~~~~~~~~~~~~~~~
rtc.cu:81:2: error: no matching function for call to 'hipGetErrorName'
   81 |         CHECK_CUDA_ERROR_EXIT(
      |         ^~~~~~~~~~~~~~~~~~~~~~
   82 |                 cuModuleGetFunction(&kernel, module, "kernelHello"));
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:25:37: note: expanded from macro 'CHECK_CUDA_ERROR_EXIT'
   25 | #define CHECK_CUDA_ERROR_EXIT(expr) CHECK_CUDA_ERROR(expr, exit(-1))
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:17:4: note: expanded from macro 'CHECK_CUDA_ERROR'
   17 |                         cuGetErrorName(__result, &__err_name);               \
      |                         ^~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:131:24: note: expanded from macro 'cuGetErrorName'
  131 | #define cuGetErrorName __cu(GetErrorName)
      |                        ^~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:72:21: note: expanded from macro '__cu'
   72 | # define __cu(name)     hip##name
      |                         ^~~~~~~~~
<scratch space>:334:1: note: expanded from here
  334 | hipGetErrorName
      | ^~~~~~~~~~~~~~~
/usr/include/hip/hip_runtime_api.h:2486:13: note: candidate function not viable: requires single argument 'hip_error', but 2 arguments were provided
 2486 | const char* hipGetErrorName(hipError_t hip_error);
      |             ^               ~~~~~~~~~~~~~~~~~~~~
rtc.cu:85:2: error: no matching function for call to 'hipGetErrorName'
   85 |         CHECK_CUDA_ERROR_EXIT(hipModuleLaunchKernel(kernel, 1, 1, 1, 1, 1, 1, 0,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   86 |                                                     NULL, NULL, NULL));
      |                                                     ~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:25:37: note: expanded from macro 'CHECK_CUDA_ERROR_EXIT'
   25 | #define CHECK_CUDA_ERROR_EXIT(expr) CHECK_CUDA_ERROR(expr, exit(-1))
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:17:4: note: expanded from macro 'CHECK_CUDA_ERROR'
   17 |                         cuGetErrorName(__result, &__err_name);               \
      |                         ^~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:131:24: note: expanded from macro 'cuGetErrorName'
  131 | #define cuGetErrorName __cu(GetErrorName)
      |                        ^~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:72:21: note: expanded from macro '__cu'
   72 | # define __cu(name)     hip##name
      |                         ^~~~~~~~~
<scratch space>:338:1: note: expanded from here
  338 | hipGetErrorName
      | ^~~~~~~~~~~~~~~
/usr/include/hip/hip_runtime_api.h:2486:13: note: candidate function not viable: requires single argument 'hip_error', but 2 arguments were provided
 2486 | const char* hipGetErrorName(hipError_t hip_error);
      |             ^               ~~~~~~~~~~~~~~~~~~~~
rtc.cu:88:2: error: no matching function for call to 'hipGetErrorName'
   88 |         CHECK_CUDA_ERROR_EXIT(cuModuleUnload(module));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:25:37: note: expanded from macro 'CHECK_CUDA_ERROR_EXIT'
   25 | #define CHECK_CUDA_ERROR_EXIT(expr) CHECK_CUDA_ERROR(expr, exit(-1))
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_helpers.h:17:4: note: expanded from macro 'CHECK_CUDA_ERROR'
   17 |                         cuGetErrorName(__result, &__err_name);               \
      |                         ^~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:131:24: note: expanded from macro 'cuGetErrorName'
  131 | #define cuGetErrorName __cu(GetErrorName)
      |                        ^~~~~~~~~~~~~~~~~~
/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/cuda_adapter.h:72:21: note: expanded from macro '__cu'
   72 | # define __cu(name)     hip##name
      |                         ^~~~~~~~~
<scratch space>:342:1: note: expanded from here
  342 | hipGetErrorName
      | ^~~~~~~~~~~~~~~
/usr/include/hip/hip_runtime_api.h:2486:13: note: candidate function not viable: requires single argument 'hip_error', but 2 arguments were provided
 2486 | const char* hipGetErrorName(hipError_t hip_error);
      |             ^               ~~~~~~~~~~~~~~~~~~~~
4 errors generated when compiling for gfx906.
failed to execute:/usr/lib64/rocm/llvm/bin/clang++  -O3 --hip-device-lib-path="/usr/lib64/rocm/llvm/lib/clang/19/amdgcn/bitcode"  -o ".output/rtc.hip.o" -c -x hip rtc.cu -I/usr/include/c++/15/x86_64-redhat-linux/ -I. -Wno-unused-result -I/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda -I/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda -I/home/sda/git-repos/rtoax/test-linux//hpc/nvidia/cuda/ -DHAVE_HIP=1 -D__USE_HIP__=1 -DHAVE_HIPSOLVER=1 -DHAVE_HIPBLASLT=1 -DHAVE_HIP_FP8=1 -DHAVE_RCCL=1 -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/usr/include -I/include

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64, Physical Machine
Vers: Fedora Linux 43, Linux 6.18.5-200.fc43.x86_64, GCC 15.2.1, glibc 2.42, LLVM 21.1.8, CUDA V13.0.48, ROCm 6.4.43484