in_irq(): Skip error: implicit declaration of function ‘in_irq’
rongtao@NUC10:~/Git/tst-linux/interrupt/request_irq$ make
 KMOD BUILD request-irq.o tasklet-bh.o
In file included from /usr/src/kernels/7.0.4-200.fc44.x86_64/include/asm-generic/bug.h:31,
                 from /usr/src/kernels/7.0.4-200.fc44.x86_64/arch/x86/include/asm/bug.h:193,
                 from /usr/src/kernels/7.0.4-200.fc44.x86_64/arch/x86/include/asm/alternative.h:9,
                 from /usr/src/kernels/7.0.4-200.fc44.x86_64/arch/x86/include/asm/barrier.h:5,
                 from /usr/src/kernels/7.0.4-200.fc44.x86_64/include/linux/list.h:11,
                 from /usr/src/kernels/7.0.4-200.fc44.x86_64/include/linux/module.h:12,
                 from tasklet-bh.c:1:
tasklet-bh.c: In function ‘print_irq_status’:
tasklet-bh.c:30:64: error: implicit declaration of function ‘in_irq’ [-Wimplicit-function-declaration]
   30 |         printk(KERN_INFO "%20s in_irq        = %ld\n", prefix, in_irq());
      |                                                                ^~~~~~

Linux: commit 70e0a80a1f35 ("treewide: Remove in_irq()")
Linux: v6.18-rc2-1-g70e0a80a1f35
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Vers: Fedora Linux 44, Linux 7.0.4-200.fc44.x86_64, Clang 22.1.4, GCC 16.1.1, GLibc 2.43, bash 5.3.9