install-deps.sh: fix error on ubuntu25.04
Unsatisfied dependencies:
 gcc-14-aarch64-linux-gnu : Conflicts: gcc-multilib but 4:14.2.0-1ubuntu1 is to be installed
 gcc-multilib : Conflicts: gcc-14-aarch64-linux-gnu but 14.2.0-19ubuntu2cross1 is to be installed
Error: Unable to correct problems, you have held broken packages.
Error: The following information from --solver 3.0 may provide additional context:
   Unable to satisfy dependencies. Reached two conflicting decisions:
   1. gcc-14-aarch64-linux-gnu:amd64 is selected for install because:
      1. gcc-aarch64-linux-gnu:amd64 is selected for install
      2. gcc-aarch64-linux-gnu:amd64 Depends gcc-14-aarch64-linux-gnu (>= 14.2.0-6~)
   2. gcc-14-aarch64-linux-gnu:amd64 is selected for removal because:
      1. gcc-multilib:amd64=4:14.2.0-1ubuntu1 is selected for install
      2. gcc-14-aarch64-linux-gnu:amd64 Conflicts gcc-multilib
Running inst-deps failed!

Signed-off-by: Rong Tao <rongtao@cestc.cn>