elf/library: ctors.c: forgot return
 CC A.O           .output/ctors.a.o
ctors.c: In function ‘foo_ctor’:
ctors.c:30:1: error: control reaches end of non-void function [-Werror=return-type]
   30 | }
      | ^
cc1: all warnings being treated as errors

Signed-off-by: Rong Tao <rtoax@foxmail.com>
Vers: Kylin Linux Advanced Server V11 (Swan25), Linux 6.6.0-32.7.v2505.ky11.x86_64, GCC 12.3.1, GLibc 2.38
Envs: Arch x86_64, kvm