hpc: blas: Fix the combination of the parameters Atype, Btype and Ctype is not supported
fix commit 4eb070be713d error:

    (base) [root@muxi-1 samples]# ./blas -v -t gemmex-int8
    ...
    [10:21:55.867][HCBLAS][E]Sorry, the combination of the parameters Atype, Btype and Ctype is not supported
    ERROR: Blas cublasGemmEx(test->handle, CUBLAS_OP_T, CUBLAS_OP_T, env.m, env.n, env.k, &alpha, test->dev_A.int8, CUDA_R_8I, env.k, test->dev_B.int8, CUDA_R_8I, env.n, &beta, test->dev_C.int8, CUDA_R_8I, env.m, CUBLAS_COMPUTE_32I, CUBLAS_GEMM_DEFAULT) failed, It is not supported now

Fix: commit 4eb070be713d ("hpc: blas: add gemmex-int8 test but run failed")
Signed-off-by: Rong Tao <rongtao@cestc.cn>