kvm: playground: Fix ‘nullEntry’ is used uninitialized
exceptions.c: In function ‘createGdtTable’:
exceptions.c:56:9: error: ‘nullEntry’ is used uninitialized [-Werror=uninitialized]
   56 |         memcpy(mem, &nullEntry, 8);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
exceptions.c:45:29: note: ‘nullEntry’ declared here
   45 |         struct gdtNullEntry nullEntry;
      |                             ^~~~~~~~~

Signed-off-by: Rong Tao <rtoax@foxmail.com>