bpftrace: compile: use llvm 20 instead of 18 on Ubuntu 24.04.4 LTS aarch64
    $ make VERBOSE=1
    ....
    [  0%] Building CXX object src/CMakeFiles/required_resources.dir/required_resources.cpp.o
    cd /home/rongtao/Git/bpftrace/bpftrace/build/src && /usr/bin/c++ -DHAVE_BFD_DISASM -DHAVE_LIBDW -DHAVE_LIBPCAP -DHAVE_NAME_TO_HANDLE_AT=1 -DLIBBFD_INIT_DISASM_INFO_FOUR_ARGS_SIGNATURE -I/home/rongtao/Git/bpftrace/bpftrace/src -I/home/rongtao/Git/bpftrace/bpftrace/build/src -I/home/rongtao/Git/bpftrace/bpftrace/build -isystem /home/rongtao/Git/bpftrace/bpftrace/build/libbpf/include -isystem /usr/lib/llvm-18/include -g -std=c++20   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Werror=undef -Wpointer-arith -Wcast-align -Wwrite-strings -Wcast-qual -Wunreachable-code -Wdisabled-optimization -Wno-missing-field-initializers -MD -MT src/CMakeFiles/required_resources.dir/required_resources.cpp.o -MF CMakeFiles/required_resources.dir/required_resources.cpp.o.d -o CMakeFiles/required_resources.dir/required_resources.cpp.o -c /home/rongtao/Git/bpftrace/bpftrace/src/required_resources.cpp
    In file included from /usr/include/cereal/details/util.hpp:54,
                     from /usr/include/cereal/types/polymorphic.hpp:36,
                     from /usr/include/cereal/types/memory.hpp:423,
                     from /home/rongtao/Git/bpftrace/bpftrace/src/required_resources.cpp:3:
    /usr/lib/llvm-18/include/cxxabi.h:51:1: error: conflicting declaration of C function ‘__cxxabiv1::__cxa_exception* __cxxabiv1::__cxa_init_primary_exception(void*, std::type_info*, void (*)(void*))’
       51 | __cxa_init_primary_exception(void* object, std::type_info* tinfo, void(_LIBCXXABI_DTOR_FUNC* dest)(void*)) throw();
          | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /usr/include/c++/13/bits/exception_ptr.h:36,
                     from /usr/include/c++/13/exception:164,
                     from /usr/include/c++/13/ios:41,
                     from /usr/include/c++/13/ostream:40,
                     from /usr/include/c++/13/bits/unique_ptr.h:42,
                     from /usr/include/c++/13/memory:78,
                     from /usr/include/cereal/cereal.hpp:34,
                     from /usr/include/cereal/archives/binary.hpp:32,
                     from /home/rongtao/Git/bpftrace/bpftrace/src/required_resources.cpp:1:
    /usr/include/c++/13/bits/cxxabi_init_exception.h:70:7: note: previous declaration ‘__cxxabiv1::__cxa_refcounted_exception* __cxxabiv1::__cxa_init_primary_exception(void*, std::type_info*, void (*)(void*))’
       70 |       __cxa_init_primary_exception(void *__object, std::type_info *__tinfo,
          |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    make[2]: *** [src/CMakeFiles/required_resources.dir/build.make:79: src/CMakeFiles/required_resources.dir/required_resources.cpp.o] Error 1

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU: Cortex-X925 Cortex-A725, Arch aarch64
Vers: Ubuntu 24.04, Linux 6.17.0-1014-nvidia, APT 2.8.3, BPFTrace 0.26.0, Clang 18.1.3, DPKG 1.22.6, LibBpf 1.3.0, LLVM 18.1.3