rust: add alloc.rs but: call to unsafe function `std::alloc::alloc`
rongtao@NUC10:~/Git/tst-linux/rust/alloc$ make V=1
make: Entering directory '/home/sda/git-repos/rtoax/test-linux/rust/alloc'
 RUSTC            alloc
/usr/bin/rustc -o alloc alloc.rs
error[E0133]: call to unsafe function `std::alloc::alloc` is unsafe and requires unsafe function or block
 --> alloc.rs:5:15
  |
5 |     let ptr = alloc(layout);
  |               ^^^^^^^^^^^^^ call to unsafe function
  |
  = note: consult the function's documentation for information on how to avoid undefined behavior

error[E0133]: call to unsafe function `std::alloc::dealloc` is unsafe and requires unsafe function or block
 --> alloc.rs:6:5
  |
6 |     dealloc(ptr, layout);
  |     ^^^^^^^^^^^^^^^^^^^^ call to unsafe function
  |
  = note: consult the function's documentation for information on how to avoid undefined behavior

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0133`.

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: Arch x86_64
Vers: Fedora Linux 44 (Workstation Edition), Linux 7.1.5-200.fc44.x86_64, Make 4.4.1, Rust 1.97.1