clang: add test CompilerInstance.cpp
Error:

    rongtao@spark-d9c2:~/Git/tst-linux/compiler/llvm/samples/clang$ make V=1
    make: Entering directory '/home/rongtao/Git/tst-linux/compiler/llvm/samples/clang'
     CLANG++          .output/CompilerInstance.cpp.o
    clang++ -MMD -MT .output/CompilerInstance.cpp.o -MF .output/CompilerInstance.cpp.o.d -o .output/CompilerInstance.cpp.o -c CompilerInstance.cpp -Wno-error=unused-command-line-argument -I/usr/lib/llvm-18/include -std=c++17   -fno-exceptions -funwind-tables -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -lLLVM-18 -I.output/ -D_GNU_SOURCE -Werror -Wall
    clang++: warning: -lLLVM-18: 'linker' input unused [-Wunused-command-line-argument]
    In file included from CompilerInstance.cpp:1:
    In file included from /usr/lib/llvm-18/include/clang/Driver/Driver.h:12:
    In file included from /usr/lib/llvm-18/include/clang/Basic/Diagnostic.h:17:
    In file included from /usr/lib/llvm-18/include/clang/Basic/DiagnosticIDs.h:17:
    In file included from /usr/lib/llvm-18/include/clang/Basic/LLVM.h:21:
    In file included from /usr/lib/llvm-18/include/llvm/Support/Casting.h:18:
    /usr/lib/llvm-18/include/llvm/Support/type_traits.h:17:10: fatal error: 'type_traits' file not found
       17 | #include <type_traits>
          |          ^~~~~~~~~~~~~
    1 error generated.
    make: *** [targets/cpp.mk:12: .output/CompilerInstance.cpp.o] Error 1
    make: Leaving directory '/home/rongtao/Git/tst-linux/compiler/llvm/samples/clang'

from bpftrace clang_build.cpp.

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: Arch aarch64
Vers: Ubuntu 24.04, Linux 6.17.0-1014-nvidia, Clang 18.1.3, GCC 13.3.0, GLibc 2.39, LLVM 18.1.3, Make 4.3, bash 5.2.21