libvirt,qemu: nvdimm: nvdimm is not enabled: missing 'nvdimm' in '-M'
error: qemu-system-x86_64: -device nvdimm,id=nv0,memdev=mem0,unarmed=on: nvdimm is not enabled: missing 'nvdimm' in '-M'

Signed-off-by: Rong Tao <rongtao@cestc.cn>