ai/models/stella:
Error:

$ ./xformers.py
Traceback (most recent call last):
  File "/LLM-MODEL/./stella-base-zh-2-1.py", line 9, in <module>
    batch_data = tokenizer(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3067, in __call__
    raise ValueError("You need to specify either `text` or `text_target`.")
ValueError: You need to specify either `text` or `text_target`.

modelscope==1.34.0
sentence-transformers==5.3.0.dev0
transformers==4.57.3

Signed-off-by: Rong Tao <rtoax@foxmail.com>
Envs: CPU Hygon C86-4G (OPN:7470), Arch x86_64, Physical Machine
Vers: CCLinux 22.09.2, Linux 5.15.131-28.cl9.x86_64, Python 3.10.10