mpich: Fix  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      CC  MPI_Abort.c to MPI_Abort.o
    In file included from /usr/include/bits/libc-header-start.h:33,
                     from /usr/include/stdint.h:26,
                     from /usr/lib/gcc/x86_64-redhat-linux/8/include/stdint.h:9,
                     from /usr/include/mpich-x86_64/mpi.h:59,
                     from MPI_Abort.c:1:
    /usr/include/features.h:381:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
     #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
        ^~~~~~~
    cc1: all warnings being treated as errors
    make: *** [Makefile:64: MPI_Abort.o] Error 1

Signed-off-by: Rong Tao <rtoax@foxmail.com>