bpf/insn: cgroup_from_id.c: must have EXIT insn
bpf_cgroup_from_id not support kprobe, but support tracepoint:

kprobe:
    rongtao@NUC10:~/Git/tst-linux/bpf/c$ sudo ./kprobe cgroup_from_id
    struct cgroup *bpf_cgroup_from_id(u64 cgid);
    void bpf_cgroup_release(struct cgroup *cgrp);
    Prog cgroup_from_id has 8 insns
    ERROR: failed to load prog 'Permission denied'

tracepoint:
    rongtao@NUC10:~/Git/tst-linux/bpf/c$ sudo ./kprobe cgroup_from_id tracepoint
    ...
    74096         ; R0_w=ptr_or_null_cgroup(id=2,ref_obj_id=2) refs=2
    2: (55) if r0 != 0x0 goto pc+1 4: R0_w=ptr_cgroup(ref_obj_id=2) R10=fp0 refs=2
    4: (bf) r1 = r0                       ; R0_w=ptr_cgroup(ref_obj_id=2) R1_w=ptr_cgroup(ref_obj_id=2) refs=2
    5: (85) call bpf_cgroup_release#74111         ;
    6: (b7) r0 = 0                        ; R0_w=0
    7: (95) exit
    Tracepoint sys_enter_nanosleep(), test with 'sleep 0.1'.

Fix: commit ed739a271628 ("bpf/c: test cgroup_from_id but failed")
Link: https://docs.ebpf.io/linux/kfuncs/bpf_cgroup_from_id/
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64
Versions: Fedora Linux 43, Kernel 6.17.7-300.fc43.x86_64, GCC 15.2.1, glibc 2.42, LLVM 21.1.5, BCC 0.35.0, LIBBPF 1.6.1