c: struct.c: forgot message for _Static_assert()
 CC               .output/struct.o
struct.c:26:54: error: expected ‘,’ before ‘)’ token
 _Static_assert(sizeof(struct test_bf) == TEST_BF_SIZE);
                                                      ^
cc1: error: unrecognized command line option ‘-Wno-initializer-overrides’ [-Werror]
cc1: error: unrecognized command line option ‘-Wno-gnu-designator’ [-Werror]

Signed-off-by: Rong Tao <rtoax@foxmail.com>
Vers: Kylin Linux Advanced Server V10 (Halberd), Linux 4.19.90-89.11.v2401.ky10.aarch64, GCC 7.3.0, GLibc 2.28
Envs: Arch aarch64