bpftrace/playground: loop.bpf.c: fix: unreachable insn N
Error:

    [rongtao@nuc10vm-centos9 playground]$ sudo  ./loop.bt -v
    WARNING: Kernel version (5.14.0-721.el9.x86_64) is lower than the minimum supported kernel version (5.15.0). Some features/scripts may not work as expected.
    ERROR: Error loading BPF program for begin_1. Error code: -22.
    Kernel error log:
    unreachable insn 8
    processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

    [rongtao@nuc10vm-centos9 playground]$ llvm-objdump -d .output/loop.bpf.o

    .output/loop.bpf.o:	file format elf64-bpf

    Disassembly of section .text:

    0000000000000000 <__bpf_count>:
           0:	b7 01 00 00 0a 00 00 00	r1 = 0xa
           1:	18 02 00 00 60 00 00 00 00 00 00 00 00 00 00 00	r2 = 0x60 ll
           3:	b7 03 00 00 00 00 00 00	r3 = 0x0
           4:	b7 04 00 00 00 00 00 00	r4 = 0x0
           5:	85 00 00 00 b5 00 00 00	call 0xb5
           6:	b7 00 00 00 00 00 00 00	r0 = 0x0
           7:	95 00 00 00 00 00 00 00	exit
           8:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0x0 ll
          10:	61 10 00 00 00 00 00 00	w0 = *(u32 *)(r1 + 0x0)
          11:	95 00 00 00 00 00 00 00	exit

    0000000000000060 <loop_callback>:
          12:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0x0 ll
          14:	61 12 00 00 00 00 00 00	w2 = *(u32 *)(r1 + 0x0)
          15:	04 02 00 00 01 00 00 00	w2 += 0x1
          16:	63 21 00 00 00 00 00 00	*(u32 *)(r1 + 0x0) = w2
          17:	b4 00 00 00 00 00 00 00	w0 = 0x0
          18:	95 00 00 00 00 00 00 00	exit

Now:

    [rongtao@nuc10vm-centos9 playground]$ llvm-objdump -d .output/loop.bpf.o

    .output/loop.bpf.o:	file format elf64-bpf

    Disassembly of section .text:

    0000000000000000 <__bpf_count>:
           0:	b7 01 00 00 0a 00 00 00	r1 = 0xa
           1:	18 02 00 00 40 00 00 00 00 00 00 00 00 00 00 00	r2 = 0x40 ll
           3:	b7 03 00 00 00 00 00 00	r3 = 0x0
           4:	b7 04 00 00 00 00 00 00	r4 = 0x0
           5:	85 00 00 00 b5 00 00 00	call 0xb5
           6:	b7 00 00 00 00 00 00 00	r0 = 0x0
           7:	95 00 00 00 00 00 00 00	exit

    0000000000000040 <loop_callback>:
           8:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0x0 ll
          10:	61 12 00 00 00 00 00 00	w2 = *(u32 *)(r1 + 0x0)
          11:	04 02 00 00 01 00 00 00	w2 += 0x1
          12:	63 21 00 00 00 00 00 00	*(u32 *)(r1 + 0x0) = w2
          13:	b4 00 00 00 00 00 00 00	w0 = 0x0
          14:	95 00 00 00 00 00 00 00	exit

Fixes: 0af99269bde6 ("bpf_loop: try call bpf_loop() in bpftrace stdlib c interop (todo)")
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64, kvm
Vers: CentOS Stream 9, Linux 5.14.0-721.el9.x86_64, Binutils 2.35.2, BPFTrace 0.26.0, GCC 11.5.0, GLibc 2.34, LibBpf 1.8.0