libbpf: Makefile: fix compile errors on opencloudos
  LD  config-map
gcc -o config-map config-map.o trace_helpers.o libbpf_wrapper.o -lbpf -O0 -Wall -g
/usr/bin/ld: trace_helpers.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
//usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:284: config-map] Error 1

Signed-off-by: Rong Tao <rongtao@cestc.cn>