netlink: test NETLINK_KOBJECT_UEVENT
kata-containers agent has uevent code:

    unsafe {
        let fd = libc::socket(
            libc::AF_NETLINK,
            libc::SOCK_DGRAM | libc::SOCK_CLOEXEC,
            protocols::NETLINK_KOBJECT_UEVENT as libc::c_int,
        );
        socket = TokioSocket::from_raw_fd(fd);
    }

if vmlinuz+initrd start a VM with qemu:

....
[    6.089523][  0] NMI watchdog: Perf NMI watchdog permanently disabled
[    6.103610][  0] Freeing unused decrypted memory: 2036K
[    6.112081][  0] Freeing unused kernel image memory: 2500K
[    6.113947][  0] Write protecting the kernel read-only data: 20480k
[    6.133976][  0] Freeing unused kernel image memory: 2032K
[    6.137165][  0] Freeing unused kernel image memory: 100K
[    6.139130][  0] Run /init as init process
{"msg":"mount source=\"proc\", dest=\"/proc\", fs_type=\"proc\", options=\"\"","level":"INFO","ts":"2025-05-19T10:07:11.63514}
{"msg":"mount source=\"sysfs\", dest=\"/sys\", fs_type=\"sysfs\", options=\"\"","level":"INFO","ts":"2025-05-19T10:07:11.6352}
{"msg":"mount source=\"dev\", dest=\"/dev\", fs_type=\"devtmpfs\", options=\"\"","level":"INFO","ts":"2025-05-19T10:07:11.635}
{"msg":"mount source=\"tmpfs\", dest=\"/dev/shm\", fs_type=\"tmpfs\", options=\"\"","level":"INFO","ts":"2025-05-19T10:07:11.}
{"msg":"mount source=\"devpts\", dest=\"/dev/pts\", fs_type=\"devpts\", options=\"\"","level":"INFO","ts":"2025-05-19T10:07:1}
{"msg":"mount source=\"tmpfs\", dest=\"/run\", fs_type=\"tmpfs\", options=\"\"","level":"INFO","ts":"2025-05-19T10:07:11.6353}
{"msg":"mount source=\"tmpfs\", dest=\"/sys/fs/cgroup\", fs_type=\"tmpfs\", options=\"mode=755\"","level":"INFO","ts":"2025-0}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/cpuset\", fs_type=\"cgroup\", options=\"cpuset\"","level":"INFO","ts":}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/cpu\", fs_type=\"cgroup\", options=\"cpu\"","level":"INFO","ts":"2025-}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/cpuacct\", fs_type=\"cgroup\", options=\"cpuacct\"","level":"INFO","ts}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/blkio\", fs_type=\"cgroup\", options=\"blkio\"","level":"INFO","ts":"2}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/memory\", fs_type=\"cgroup\", options=\"memory\"","level":"INFO","ts":}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/devices\", fs_type=\"cgroup\", options=\"devices\"","level":"INFO","ts}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/freezer\", fs_type=\"cgroup\", options=\"freezer\"","level":"INFO","ts}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/net_cls\", fs_type=\"cgroup\", options=\"net_cls\"","level":"INFO","ts}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/perf_event\", fs_type=\"cgroup\", options=\"perf_event\"","level":"INF}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/net_prio\", fs_type=\"cgroup\", options=\"net_prio\"","level":"INFO","}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/hugetlb\", fs_type=\"cgroup\", options=\"hugetlb\"","level":"INFO","ts}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/pids\", fs_type=\"cgroup\", options=\"pids\"","level":"INFO","ts":"202}
{"msg":"mount source=\"cgroup\", dest=\"/sys/fs/cgroup/rdma\", fs_type=\"cgroup\", options=\"rdma\"","level":"INFO","ts":"202}
{"msg":"mount source=\"tmpfs\", dest=\"/sys/fs/cgroup\", fs_type=\"tmpfs\", options=\"mode=755\"","level":"INFO","ts":"2025-0}
Error: socket err: EAFNOSUPPORT: Address family not supported by protocol
{[    6.275773][  0] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[    6.275773][  0]
[    6.279061][  0] CPU: 0 PID: 1 Comm: init Not tainted 4.19.90-89.16.v2401.ky10.x86_64 #1
[    6.281740][  0] Source Version: a9bf83890f864cddb0c32240d1b5e5d4e850b92f
[    6.283736][  0] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS rel-1.14.0-0-g155821a1990b-prebuilt.qemu.org 04/4
[    6.286954][  0] Call Trace:
[    6.288153][  0]  dump_stack+0x66/0x81
[    6.289413][  0]  panic+0x119/0x2c4
[    6.290627][  0]  do_exit+0x821/0xc00
[    6.292003][  0]  do_group_exit+0x3a/0xa0
[    6.293214][  0]  __x64_sys_exit_group+0x14/0x20
[    6.294631][  0]  do_syscall_64+0x5f/0x240
[    6.296172][  0]  entry_SYSCALL_64_after_hwframe+0x5c/0xc1
[    6.298202][  0] RIP: 0033:0x7f2257fee03b
[    6.299626][  0] Code: 74 ff ff eb 0c 48 89 ef 41 83 cc ff e8 fe 8d ff ff 5a 44 89 e0 5b 5d 41 5c 41 5d 41 5e 41 5f c3 48 a
[    6.305186][  0] RSP: 002b:00007ffd432e0598 EFLAGS: 00000246 ORIG_RAX: 00000000000000e7
[    6.307682][  0] RAX: ffffffffffffffda RBX: 00007f2257b8ebb0 RCX: 00007f2257fee03b
[    6.310202][  0] RDX: 00007f22581fbf20 RSI: 0000000000000000 RDI: 0000000000000001
[    6.312752][  0] RBP: 0000000000000001 R08: 0000000000000001 R09: 0000000000000000
[    6.315304][  0] R10: 0000000000000000 R11: 0000000000000246 R12: 00007ffd432e05f8
[    6.317779][  0] R13: 00007ffd432e0608 R14: 0000000000000000 R15: 0000000000000000
[    6.320110][  0] Kernel Offset: 0x21000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbffffff)
[    6.323709][  0] Rebooting in 1 seconds..

Link: https://github.com/kata-containers/kata-containers.git
Signed-off-by: Rong Tao <rongtao@cestc.cn>