fakeCUDA: cuda_adapter.h: Fix ‘cudaDataType_t’ redefined
[15:46:12] CXX SO.o blas-hip.cpp -> .output/blas-hip.cpp.so.o
In file included from cuda_compat.h:81,
                 from blas.hpp:6,
                 from blas.cpp:8,
                 from blas-hip.cpp:16:
cuda_adapter.h:1457:9: warning: ‘cudaDataType_t’ redefined
 1457 | #define cudaDataType_t cudaDataType
      |         ^~~~~~~~~~~~~~
blas-hip.cpp:8:9: note: this is the location of the previous definition
    8 | #define cudaDataType_t  hipblasDatatype_t
      |         ^~~~~~~~~~~~~~
cuda_adapter.h:25:25: error: conflicting declaration of C function ‘hipblasStatus_t hipblasGemmEx(hipblasHandle_t, hipblasOperation_t, hipblasOperation_t, int, int, int, const void*, const void*, hipDataType, int, const void*, hipDataType, int, const void*, void*, hipDataType, int, hipDataType, hipblasGemmAlgo_t)’
   25 | # define __cu(name)     hip##name
      |                         ^~~
cuda_adapter.h:1083:9: note: in expansion of macro ‘__cu’
 1083 |         __cu(blasGemmEx(handle, transa, transb, m, n, k, alpha, A, Atype, lda, \
      |         ^~~~
blas.hpp:158:16: note: in expansion of macro ‘cublasGemmEx’
  158 | cublasStatus_t cublasGemmEx(cublasHandle_t handle,
      |                ^~~~~~~~~~~~
In file included from cuda_compat.h:72:
/usr/include/hipblas/hipblas.h:31114:32: note: previous declaration ‘hipblasStatus_t hipblasGemmEx(hipblasHandle_t, hipblasOperation_t, hipblasOperation_t, int, int, int, const void*, const void*, hipblasDatatype_t, int, const void*, hipblasDatatype_t, int, const void*, void*, hipblasDatatype_t, int, hipblasDatatype_t, hipblasGemmAlgo_t)’
31114 | HIPBLAS_EXPORT hipblasStatus_t hipblasGemmEx(hipblasHandle_t    handle,
      |                                ^~~~~~~~~~~~~

Fix: commit 13f36a5fd4a6 ("amd rocm hip support .cu suffix")
Signed-off-by: Rong Tao <rongtao@cestc.cn>