[TODO] libbpf: kprobe.bpf.c: fix struct filename{} change
    $ make
    Found struct bpf_devmap_val{}
     BPF      .output/kprobe.bpf.o
    kprobe.bpf.c:34:33: error: no member named 'name' in 'struct filename'
       34 |         filename = BPF_CORE_READ(name, name);
          |                    ~~~~~~~~~~~~~~~~~~~~^~~~~
    ....

    $ sudo bpftrace -lv 'struct filename'
    struct filename {
    	struct __filename_head;
    	const char iname[168];
    };

TODO:

rongtao@ubuntu:~/Git/tst-linux/bpf/libbpf$ sudo ./kprobe
libbpf: prog 'do_execveat_common': BPF program load failed: -EACCES
libbpf: prog 'do_execveat_common': failed to load: -EACCES
libbpf: failed to load object 'kprobe_bpf'
libbpf: failed to load BPF skeleton 'kprobe_bpf': -EACCES
0: R1=ctx() R10=fp0
; int BPF_KPROBE(do_execveat_common, int fd, struct filename *name) @ kprobe.bpf.c:25
0: (bf) r8 = r1                       ; R1=ctx() R8=ctx()
1: (79) r7 = *(u64 *)(r8 +104)        ; R7=scalar() R8=ctx()
; pid = bpf_get_current_pid_tgid() >> 32; @ kprobe.bpf.c:29
2: (85) call bpf_get_current_pid_tgid#14      ; R0=scalar()
3: (bf) r6 = r0                       ; R0=scalar(id=1) R6=scalar(id=1)
4: (b7) r1 = 0                        ; R1=0
5: (0f) r7 += r1                      ; R1=0 R7=scalar()
6: (bf) r1 = r10                      ; R1=fp0 R10=fp0
7: (07) r1 += -8                      ; R1=fp-8
; filename = BPF_CORE_READ(fhead, name); @ kprobe.bpf.c:37
8: (b4) w2 = 8                        ; R2=8
9: (bf) r3 = r7                       ; R3=scalar(id=2) R7=scalar(id=2)
10: (85) call bpf_probe_read_kernel#113       ; R0=scalar() fp-8=mmmmmmmm
11: (79) r7 = *(u64 *)(r10 -8)        ; R7=scalar() R10=fp0 fp-8=mmmmmmmm
; kstack_id = bpf_get_stackid(ctx, &stackmap, 0); @ stack_helpers.bpf.h:37
12: (bf) r1 = r8                      ; R1=ctx() R8=ctx()
13: (18) r2 = 0xffff8db0af1a8000      ; R2=map_ptr(map=stackmap,ks=4,vs=8)
15: (b7) r3 = 0                       ; R3=0
16: (85) call bpf_get_stackid#27      ; R0=scalar()
17: (bf) r9 = r0                      ; R0=scalar(id=3) R9=scalar(id=3)
; ustack_id = bpf_get_stackid(ctx, &stackmap, BPF_F_USER_STACK); @ stack_helpers.bpf.h:39
18: (bf) r1 = r8                      ; R1=ctx() R8=ctx()
19: (18) r2 = 0xffff8db0af1a8000      ; R2=map_ptr(map=stackmap,ks=4,vs=8)
21: (b7) r3 = 256                     ; R3=256
22: (85) call bpf_get_stackid#27      ; R0=scalar()
; pid = bpf_get_current_pid_tgid() >> 32; @ kprobe.bpf.c:29
23: (77) r6 >>= 32                    ; R6=scalar(smin=0,smax=umax=0xffffffff,var_off=(0x0; 0xffffffff))
; if (kstack_id >= 0 && ustack_id >= 0) { @ stack_helpers.bpf.h:41
24: (c6) if w9 s< 0x0 goto pc+7       ; R9=scalar(smax=0x7fffffff7fffffff,umax=0xffffffff7fffffff,smin32=0,umax32=0x7fffffff,var_off=(0x0; 0xffffffff7fffffff))
25: (c6) if w0 s< 0x0 goto pc+6       ; R0=scalar(smax=0x7fffffff7fffffff,umax=0xffffffff7fffffff,smin32=0,umax32=0x7fffffff,var_off=(0x0; 0xffffffff7fffffff))
; bpf_printk("Stack kernel %d, user %d", kstack_id, ustack_id); @ stack_helpers.bpf.h:42
26: (18) r1 = 0xffff8db08b82bb9b      ; R1=map_value(map=kprobe_b.rodata,ks=4,vs=170,off=107)
28: (b4) w2 = 25                      ; R2=25
29: (bc) w3 = w9                      ; R3=scalar(smin=smin32=0,smax=umax=umax32=0x7fffffff,var_off=(0x0; 0x7fffffff)) R9=scalar(smax=0x7fffffff7fffffff,umax=0xffffffff7fffffff,smin32=0,umax32=0x7fffffff,var_off=(0x0; 0xffffffff7fffffff))
30: (bc) w4 = w0                      ; R0=scalar(smax=0x7fffffff7fffffff,umax=0xffffffff7fffffff,smin32=0,umax32=0x7fffffff,var_off=(0x0; 0xffffffff7fffffff)) R4=scalar(smin=smin32=0,smax=umax=umax32=0x7fffffff,var_off=(0x0; 0x7fffffff))
31: (85) call bpf_trace_printk#6      ; R0=scalar()
; if (filename && str_eq(filename, "ls", 2)) { @ kprobe.bpf.c:63
32: (15) if r7 == 0x0 goto pc+15      ; R7=scalar(umin=1)
; return !bpf_strncmp(a, len, b); @ string_helpers.bpf.h:10
33: (bf) r1 = r7                      ; R1=scalar(id=4,umin=1) R7=scalar(id=4,umin=1)
34: (b4) w2 = 2                       ; R2=2
35: (18) r3 = 0xffff8db0bd6ac330      ; R3=map_value(map=.rodata.str1.1,ks=4,vs=3)
37: (85) call bpf_strncmp#182
R1 type=scalar expected=fp, pkt, pkt_meta, map_key, map_value, mem, ringbuf_mem, buf, trusted_ptr_
processed 34 insns (limit 1000000) max_states_per_insn 0 total_states 3 peak_states 3 mark_read 0
Failed to load BPF object

Linux: commit 8c888b31903c ("struct filename: saner handling of long names")
Linux: v6.19-rc5-20-g8c888b31903c
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Vers: Ubuntu 26.04, Linux 7.0.0-15-generic, GCC 15.2.0, GLibc 2.43, LibBpf 1.6.3, Pahole 1.31