ai: gradient-descent.py: Fix error
rongtao@NUC10:~/Git/tst-linux/ai/algorithm$ ./gradient-descent.py
Traceback (most recent call last):
  File "/home/sda/git-repos/rtoax/test-linux/ai/algorithm/./gradient-descent.py", line 76, in <module>
    img = ax.imshow(np.log10(np.transpose(rosenbrock(x2d, y2d, a, b))),
          ^^
NameError: name 'ax' is not defined. Did you mean: 'a'?

Fix: commit c05a4c80068d ("ai: move gradient-descent.py to algorithm/")
Signed-off-by: Rong Tao <rongtao@cestc.cn>