install-deps.sh: add docker-engine for kylin V10
Error: Transaction test error:
  file /usr/bin/containerd from install of containerd-1.2.0-203.ky10.x86_64 conflicts with file from package docker-engine-18.09.0-206.p15.03.ky10.x86_64
  file /usr/bin/containerd-shim from install of containerd-1.2.0-203.ky10.x86_64 conflicts with file from package docker-engine-18.09.0-206.p15.03.ky10.x86_64

Signed-off-by: Rong Tao <rtoax@foxmail.com>
OS: Kylin Linux Advanced Server V10 (GFB)
Linux: 4.19.90-52.23.v2207.gfb01.ky10.x86_64
Vers: Podman 0.10.1, bash 5.0.18
Envs: Arch x86_64