python: numpy: Fix RecursionError: maximum recursion depth exceeded
This is caused by a conflict between the script file name and the random module
in the Python standard library or the random submodule of NumPy.

    rongtao@NUC10:~/Git/tst-linux/python/numpy$ ./random.py
    Traceback (most recent call last):
      File "/home/sda/git-repos/rtoax/test-linux/python/numpy/./random.py", line 10, in <module>
        np.random.seed(42)
        ^^^^^^^^^
      File "/usr/lib64/python3.13/site-packages/numpy/__init__.py", line 340, in __getattr__
        import numpy.random as random
      File "/usr/lib64/python3.13/site-packages/numpy/random/__init__.py", line 180, in <module>
        from . import _pickle
      File "/usr/lib64/python3.13/site-packages/numpy/random/_pickle.py", line 1, in <module>
        from .bit_generator import BitGenerator
      File "bit_generator.pyx", line 40, in init numpy.random.bit_generator
      File "/usr/lib64/python3.13/secrets.py", line 18, in <module>
        from random import SystemRandom
      File "/home/sda/git-repos/rtoax/test-linux/python/numpy/random.py", line 10, in <module>
        np.random.seed(42)
        ^^^^^^^^^
      File "/usr/lib64/python3.13/site-packages/numpy/__init__.py", line 340, in __getattr__
        import numpy.random as random
      File "/usr/lib64/python3.13/site-packages/numpy/__init__.py", line 340, in __getattr__
        import numpy.random as random
      File "/usr/lib64/python3.13/site-packages/numpy/__init__.py", line 340, in __getattr__
        import numpy.random as random
      [Previous line repeated 960 more times]
      File "<frozen importlib._bootstrap>", line 471, in _lock_unlock_module
      File "<frozen importlib._bootstrap>", line 311, in acquire
      File "<frozen importlib._bootstrap>", line 170, in __enter__
      File "<frozen importlib._bootstrap>", line 132, in setdefault
    RecursionError: maximum recursion depth exceeded

Signed-off-by: Rong Tao <rongtao@cestc.cn>